import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

void main() {
  test(
    'application dependency graph is committed and release workflows lock it',
    () {
      final lockfile = File('pubspec.lock');
      expect(lockfile.existsSync(), isTrue);
      expect(lockfile.readAsStringSync(), startsWith('# Generated by pub'));

      final lockfileDiff = Process.runSync('git', [
        'diff',
        '--exit-code',
        '--',
        'pubspec.lock',
      ]);
      expect(
        lockfileDiff.exitCode,
        0,
        reason:
            'Platform generation or dependency installation mutated pubspec.lock.\n'
            '${lockfileDiff.stdout}${lockfileDiff.stderr}',
      );

      final gitignore = File('.gitignore').readAsStringSync();
      expect(gitignore, contains('!pubspec.lock'));

      final workflowDirectory = Directory('.github/workflows');
      final workflows =
          workflowDirectory
              .listSync()
              .whereType<File>()
              .where((file) => file.path.endsWith('.yml'))
              .toList()
            ..sort((a, b) => a.path.compareTo(b.path));

      var lockedInstallCount = 0;
      for (final workflow in workflows) {
        final source = workflow.readAsStringSync();
        expect(
          RegExp(
            r'^\s*run:\s*flutter pub get\s*$',
            multiLine: true,
          ).hasMatch(source),
          isFalse,
          reason: '${workflow.path} contains an unlocked dependency install.',
        );
        lockedInstallCount += RegExp(
          r'^\s*run:\s*flutter pub get --enforce-lockfile\s*$',
          multiLine: true,
        ).allMatches(source).length;
      }

      expect(lockedInstallCount, greaterThanOrEqualTo(12));
    },
  );
}
