import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

void main() {
  test('application dependency graph is committed and release workflows lock it', () {
    final lockfile = File('pubspec.lock');
    expect(lockfile.existsSync(), isTrue);
    expect(lockfile.readAsStringSync(), startsWith('# Generated by pub'));

    final pubspec = File('pubspec.yaml').readAsStringSync();
    expect(
      RegExp(
        r'^\s*google_mobile_ads:\s*9\.0\.0\s*$',
        multiLine: true,
      ).hasMatch(pubspec),
      isTrue,
      reason:
          'The release-tested google_mobile_ads wrapper must remain exactly '
          'pinned so platform scaffolding cannot silently move the Flutter '
          'plugin before the enforced lockfile install runs.',
    );

    final lockfileDiff = Process.runSync('git', [
      'diff',
      '--exit-code',
      '--',
      'pubspec.lock',
    ]);
    expect(
      lockfileDiff.exitCode,
      0,
      reason:
          'Platform generation or dependency installation mutated pubspec.lock.\n'
          '${lockfileDiff.stdout}${lockfileDiff.stderr}',
    );

    final gitignore = File('.gitignore').readAsStringSync();
    expect(gitignore, contains('!pubspec.lock'));

    final helper = File(
      'tool/scaffold_native_preserving_sources.sh',
    ).readAsStringSync();
    expect(helper, contains('set -euo pipefail'));
    expect(helper, contains(r'flutter create . "$@" --no-pub'));
    expect(helper, contains(r'cp pubspec.yaml "$backup_dir/pubspec.yaml"'));
    expect(helper, contains(r'cp pubspec.lock "$backup_dir/pubspec.lock"'));
    expect(helper, contains('restore_sources'));
    expect(helper, contains('trap cleanup EXIT'));
    expect(helper, contains(r'cmp -s pubspec.yaml "$backup_dir/pubspec.yaml"'));
    expect(helper, contains(r'cmp -s pubspec.lock "$backup_dir/pubspec.lock"'));

    final workflowDirectory = Directory('.github/workflows');
    final workflows =
        workflowDirectory
            .listSync()
            .whereType<File>()
            .where((file) => file.path.endsWith('.yml'))
            .toList()
          ..sort((a, b) => a.path.compareTo(b.path));

    var lockedInstallCount = 0;
    var scaffoldHelperCount = 0;
    for (final workflow in workflows) {
      final source = workflow.readAsStringSync();
      expect(
        RegExp(
          r'^\s*run:\s*flutter pub get\s*$',
          multiLine: true,
        ).hasMatch(source),
        isFalse,
        reason: '${workflow.path} contains an unlocked dependency install.',
      );
      expect(
        RegExp(
          r'^\s*run:\s*flutter create\b',
          multiLine: true,
        ).hasMatch(source),
        isFalse,
        reason:
            '${workflow.path} bypasses the source-preserving scaffold helper.',
      );

      final flutterActionCount = RegExp(
        r'uses:\s*subosito/flutter-action@v2',
      ).allMatches(source).length;
      final validatedToolchainCount = RegExp(
        r"flutter-version:\s*'3\.44\.9'",
      ).allMatches(source).length;
      expect(
        validatedToolchainCount,
        flutterActionCount,
        reason:
            '${workflow.path} must pin every Flutter action to the validated '
            '3.44.9 release toolchain.',
      );

      final scaffoldMatches = RegExp(
        r'^\s*run:\s*(bash tool/scaffold_native_preserving_sources\.sh[^\n]*)$',
        multiLine: true,
      ).allMatches(source);
      for (final match in scaffoldMatches) {
        scaffoldHelperCount += 1;
        final tail = source.substring(match.end);
        final nextRun = RegExp(
          r'^\s*run:\s*([^\n]+)$',
          multiLine: true,
        ).firstMatch(tail);
        expect(
          nextRun,
          isNotNull,
          reason:
              '${workflow.path} has a scaffold helper step without a following '
              'dependency installation.',
        );
        expect(
          nextRun!.group(1)!.trim(),
          'flutter pub get --enforce-lockfile',
          reason:
              '${workflow.path} must enforce the committed lock immediately '
              'after native shell materialization.',
        );
      }

      lockedInstallCount += RegExp(
        r'^\s*run:\s*flutter pub get --enforce-lockfile\s*$',
        multiLine: true,
      ).allMatches(source).length;
    }

    expect(
      scaffoldHelperCount,
      greaterThanOrEqualTo(6),
      reason:
          'Every native CI/release scaffold path must use the preserving helper.',
    );
    expect(
      lockedInstallCount,
      greaterThanOrEqualTo(10),
      reason:
          'All active build/release workflows must keep the committed lockfile '
          'enforced.',
    );
  });
}
