import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

void main() {
  test(
    'application dependency graph is committed and release workflows lock it',
    () {
      final lockfile = File('pubspec.lock');
      expect(lockfile.existsSync(), isTrue);
      expect(lockfile.readAsStringSync(), startsWith('# Generated by pub'));

      final pubspec = File('pubspec.yaml').readAsStringSync();
      expect(
        RegExp(
          r'^\s*google_mobile_ads:\s*9\.0\.0\s*$',
          multiLine: true,
        ).hasMatch(pubspec),
        isTrue,
        reason:
            'The release-tested google_mobile_ads wrapper must remain exactly '
            'pinned so platform scaffolding cannot silently move the Flutter '
            'plugin before the enforced lockfile install runs.',
      );

      final lockfileDiff = Process.runSync('git', [
        'diff',
        '--exit-code',
        '--',
        'pubspec.lock',
      ]);
      expect(
        lockfileDiff.exitCode,
        0,
        reason:
            'Platform generation or dependency installation mutated pubspec.lock.\n'
            '${lockfileDiff.stdout}${lockfileDiff.stderr}',
      );

      final gitignore = File('.gitignore').readAsStringSync();
      expect(gitignore, contains('!pubspec.lock'));

      final workflowDirectory = Directory('.github/workflows');
      final workflows =
          workflowDirectory
              .listSync()
              .whereType<File>()
              .where((file) => file.path.endsWith('.yml'))
              .toList()
            ..sort((a, b) => a.path.compareTo(b.path));

      var lockedInstallCount = 0;
      for (final workflow in workflows) {
        final source = workflow.readAsStringSync();
        expect(
          RegExp(
            r'^\s*run:\s*flutter pub get\s*$',
            multiLine: true,
          ).hasMatch(source),
          isFalse,
          reason: '${workflow.path} contains an unlocked dependency install.',
        );

        final flutterActionCount = RegExp(
          r'uses:\s*subosito/flutter-action@v2',
        ).allMatches(source).length;
        final validatedToolchainCount = RegExp(
          r"flutter-version:\s*'3\.44\.9'",
        ).allMatches(source).length;
        expect(
          validatedToolchainCount,
          flutterActionCount,
          reason:
              '${workflow.path} must pin every Flutter action to the validated '
              '3.44.9 release toolchain. A moving stable channel can invalidate '
              'the committed lockfile without any repository change.',
        );

        for (final match in RegExp(
          r'^\s*run:\s*(flutter create[^\n]*)$',
          multiLine: true,
        ).allMatches(source)) {
          expect(
            match.group(1),
            contains('--no-pub'),
            reason:
                '${workflow.path} lets flutter create resolve packages before '
                'the enforced lockfile install. Platform scaffolding must use '
                '--no-pub so the committed dependency graph stays byte-stable.',
          );

          final tail = source.substring(match.end);
          final nextRun = RegExp(
            r'^\s*run:\s*([^\n]+)$',
            multiLine: true,
          ).firstMatch(tail);
          expect(
            nextRun,
            isNotNull,
            reason:
                '${workflow.path} has a scaffold step without a following '
                'dependency installation.',
          );
          expect(
            nextRun!.group(1)!.trim(),
            'flutter pub get --enforce-lockfile',
            reason:
                '${workflow.path} runs another tool after flutter create before '
                'the enforced dependency install. Dart/Flutter tooling can '
                'otherwise resolve packages and rewrite pubspec.lock.',
          );
        }

        lockedInstallCount += RegExp(
          r'^\s*run:\s*flutter pub get --enforce-lockfile\s*$',
          multiLine: true,
        ).allMatches(source).length;
      }

      expect(
        lockedInstallCount,
        greaterThanOrEqualTo(10),
        reason:
            'All active build/release workflows must keep the committed lockfile '
            'enforced. Obsolete parallel Android signing and Pages preview '
            'workflows were removed, leaving one canonical path per release '
            'surface and at least 10 locked dependency installs.',
      );
    },
  );
}
