import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

import 'app_language.dart';
import 'flagship.dart';
import 'language_bridge.dart';
import 'theme.dart';
import 'widgets.dart';

class LocalizedPremiumScreen extends StatefulWidget {
  const LocalizedPremiumScreen({required this.source, required this.language, super.key});

  final String source;
  final MysticLanguage language;

  @override
  State<LocalizedPremiumScreen> createState() => _LocalizedPremiumScreenState();
}

class _LocalizedPremiumScreenState extends State<LocalizedPremiumScreen> {
  int plan = 2;

  String t({required String en, required String es, required String fr, required String pt, required String tr, required String it, required String de}) => localized(widget.language.appLanguage, english: en, spanish: es, french: fr, portugueseBrazil: pt, turkish: tr, italian: it, german: de);

  @override
  Widget build(BuildContext context) => Scaffold(body: MysticBackground(child: ListView(padding: const EdgeInsets.fromLTRB(20, 12, 20, 30), children: [
        Row(children: [IconButton(onPressed: () => Navigator.pop(context), icon: const Icon(Icons.close)), const Spacer(), TextButton(onPressed: _restore, child: Text(t(en: 'Restore', es: 'Restaurar', fr: 'Restaurer', pt: 'Restaurar', tr: 'Geri yükle', it: 'Ripristina', de: 'Wiederherstellen')))]),
        Container(width: 74, height: 74, alignment: Alignment.center, decoration: BoxDecoration(shape: BoxShape.circle, gradient: const RadialGradient(colors: [Color(0xFFFFE5A3), Color(0xFF9D6D26)]), boxShadow: [BoxShadow(color: MysticColors.gold.withValues(alpha: .32), blurRadius: 32)]), child: const Text('✦', style: TextStyle(fontSize: 39, color: MysticColors.ink))),
        const SizedBox(height: 12),
        Text(_headline(), textAlign: TextAlign.center, style: Theme.of(context).textTheme.displaySmall),
        const SizedBox(height: 12),
        Text(_body(), textAlign: TextAlign.center, style: Theme.of(context).textTheme.bodyLarge),
        const SizedBox(height: 22),
        if (kIsWeb) _notice(t(en: 'WEB EARLY ACCESS • No payment is collected in this release.', es: 'ACCESO WEB ANTICIPADO • Esta versión no cobra pagos.', fr: 'ACCÈS WEB ANTICIPÉ • Aucun paiement dans cette version.', pt: 'ACESSO WEB ANTECIPADO • Nenhum pagamento nesta versão.', tr: 'WEB ERKEN ERİŞİM • Bu sürümde ödeme alınmaz.', it: 'ACCESSO WEB ANTICIPATO • Nessun pagamento in questa versione.', de: 'WEB-FRÜHZUGANG • In dieser Version erfolgt keine Zahlung.')),
        if (kIsWeb) const SizedBox(height: 18),
        ..._benefits().map((item) => Padding(padding: const EdgeInsets.only(bottom: 11), child: Row(children: [const CircleAvatar(radius: 11, backgroundColor: MysticColors.gold, child: Icon(Icons.check, size: 14, color: MysticColors.ink)), const SizedBox(width: 11), Expanded(child: Text(item, style: Theme.of(context).textTheme.bodyLarge))]))),
        const SizedBox(height: 12),
        SizedBox(height: 128, child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [
          Expanded(child: _plan(0, t(en: 'Weekly', es: 'Semanal', fr: 'Hebdo', pt: 'Semanal', tr: 'Haftalık', it: 'Settimanale', de: 'Wöchentlich'), r'$4.99', t(en: 'per week', es: 'por semana', fr: 'par semaine', pt: 'por semana', tr: 'haftalık', it: 'a settimana', de: 'pro Woche'))),
          const SizedBox(width: 8),
          Expanded(child: _plan(1, t(en: 'Monthly', es: 'Mensual', fr: 'Mensuel', pt: 'Mensal', tr: 'Aylık', it: 'Mensile', de: 'Monatlich'), r'$9.99', t(en: 'per month', es: 'por mes', fr: 'par mois', pt: 'por mês', tr: 'aylık', it: 'al mese', de: 'pro Monat'))),
          const SizedBox(width: 8),
          Expanded(child: _plan(2, t(en: 'Yearly', es: 'Anual', fr: 'Annuel', pt: 'Anual', tr: 'Yıllık', it: 'Annuale', de: 'Jährlich'), r'$39.99', r'$3.33/month', badge: t(en: 'SAVE 67%', es: 'AHORRA 67%', fr: 'ÉCONOMISEZ 67%', pt: 'ECONOMIZE 67%', tr: '%67 TASARRUF', it: 'RISPARMIA 67%', de: '67% SPAREN'))),
        ])),
        const SizedBox(height: 18),
        GoldButton(label: kIsWeb ? t(en: 'Mystic Plus mobile launch', es: 'Lanzamiento móvil de Mystic Plus', fr: 'Lancement mobile Mystic Plus', pt: 'Lançamento móvel do Mystic Plus', tr: 'Mystic Plus mobil çıkışı', it: 'Lancio mobile di Mystic Plus', de: 'Mystic Plus Mobilstart') : plan == 2 ? t(en: 'Start my 7-day free trial', es: 'Iniciar prueba gratuita de 7 días', fr: 'Démarrer mon essai gratuit de 7 jours', pt: 'Iniciar teste grátis de 7 dias', tr: '7 günlük ücretsiz denemeyi başlat', it: 'Inizia la prova gratuita di 7 giorni', de: '7-tägige Testphase starten') : t(en: 'Continue', es: 'Continuar', fr: 'Continuer', pt: 'Continuar', tr: 'Devam et', it: 'Continua', de: 'Weiter'), onPressed: _beginPurchase, icon: kIsWeb ? Icons.phone_iphone_rounded : Icons.lock_open_rounded),
        const SizedBox(height: 10),
        Text(kIsWeb ? t(en: 'Planned pricing is shown for transparency. Final localized pricing appears in the official store checkout.', es: 'Los precios previstos se muestran con transparencia. El precio final localizado aparecerá en la tienda oficial.', fr: 'Les tarifs prévus sont affichés par transparence. Le prix localisé final apparaîtra dans la boutique officielle.', pt: 'Os preços planejados são exibidos com transparência. O preço local final aparecerá na loja oficial.', tr: 'Planlanan fiyatlar şeffaflık için gösterilir. Kesin yerel fiyat resmi mağaza ödeme ekranında görünür.', it: 'I prezzi previsti sono mostrati per trasparenza. Il prezzo locale finale apparirà nello store ufficiale.', de: 'Geplante Preise werden transparent gezeigt. Der endgültige lokale Preis erscheint im offiziellen Store.') : t(en: 'Subscription purchases use the official Apple or Google checkout.', es: 'Las suscripciones usan el pago oficial de Apple o Google.', fr: 'Les abonnements utilisent le paiement officiel Apple ou Google.', pt: 'As assinaturas usam o checkout oficial da Apple ou Google.', tr: 'Abonelik satın alımları resmi Apple veya Google ödeme ekranını kullanır.', it: 'Gli abbonamenti usano il checkout ufficiale Apple o Google.', de: 'Abonnements nutzen den offiziellen Apple- oder Google-Checkout.'), textAlign: TextAlign.center, style: Theme.of(context).textTheme.bodyMedium),
        Row(mainAxisAlignment: MainAxisAlignment.center, children: [TextButton(onPressed: () => _legal(false), child: Text(t(en: 'Terms', es: 'Términos', fr: 'Conditions', pt: 'Termos', tr: 'Koşullar', it: 'Termini', de: 'Bedingungen'))), const Text('•', style: TextStyle(color: MysticColors.muted)), TextButton(onPressed: () => _legal(true), child: Text(t(en: 'Privacy', es: 'Privacidad', fr: 'Confidentialité', pt: 'Privacidade', tr: 'Gizlilik', it: 'Privacy', de: 'Datenschutz')))]),
      ])));

  String _headline() => widget.source == 'daily_limit' ? t(en: 'Your insight does not\nhave to stop here.', es: 'Tu claridad no tiene\nque terminar aquí.', fr: 'Votre réflexion ne doit\npas s’arrêter ici.', pt: 'Sua percepção não precisa\nparar aqui.', tr: 'İçgörün burada\nbitmek zorunda değil.', it: 'La tua intuizione non deve\nfermarsi qui.', de: 'Deine Erkenntnis muss\nhier nicht enden.') : t(en: 'Make space for\ndeeper insight.', es: 'Abre espacio para\nuna visión más profunda.', fr: 'Faites place à\nune réflexion plus profonde.', pt: 'Abra espaço para\nmais profundidade.', tr: 'Daha derin içgörüye\nyer aç.', it: 'Fai spazio a\nuna visione più profonda.', de: 'Schaffe Raum für\ntiefere Erkenntnis.');

  String _body() => t(en: 'Unlock unlimited readings, premium spreads, extended Oracle dialogue, and your complete pattern history.', es: 'Desbloquea lecturas ilimitadas, tiradas premium, diálogo extendido con el Oráculo y todo tu historial de patrones.', fr: 'Débloquez les tirages illimités, les tirages premium, le dialogue Oracle prolongé et tout votre historique.', pt: 'Desbloqueie leituras ilimitadas, tiragens premium, diálogo estendido com o Oráculo e todo o seu histórico.', tr: 'Sınırsız okumaları, premium açılımları, uzun Oracle diyaloğunu ve tam örüntü geçmişini aç.', it: 'Sblocca letture illimitate, stese premium, dialogo esteso con l’Oracolo e lo storico completo.', de: 'Schalte unbegrenzte Legungen, Premium-Spreads, längere Oracle-Dialoge und deine vollständige Musterhistorie frei.');

  List<String> _benefits() => [
    t(en: 'Unlimited readings and every spread', es: 'Lecturas ilimitadas y todas las tiradas', fr: 'Tirages illimités et toutes les méthodes', pt: 'Leituras ilimitadas e todas as tiragens', tr: 'Sınırsız okuma ve tüm açılımlar', it: 'Letture illimitate e tutte le stese', de: 'Unbegrenzte Legungen und alle Spreads'),
    t(en: 'Unlimited Oracle follow-up dialogue', es: 'Diálogo ilimitado con el Oráculo', fr: 'Dialogue Oracle illimité', pt: 'Diálogo ilimitado com o Oráculo', tr: 'Sınırsız Oracle takip diyaloğu', it: 'Dialogo illimitato con l’Oracolo', de: 'Unbegrenzter Oracle-Folgedialog'),
    t(en: 'Complete journal and pattern history', es: 'Diario e historial de patrones completos', fr: 'Journal et historique complets', pt: 'Diário e histórico de padrões completos', tr: 'Tam günlük ve örüntü geçmişi', it: 'Diario e storico completi', de: 'Vollständiges Journal und Musterverlauf'),
    t(en: 'All premium tarot deck themes', es: 'Todos los temas premium', fr: 'Tous les thèmes premium', pt: 'Todos os temas premium', tr: 'Tüm premium deste temaları', it: 'Tutti i temi premium', de: 'Alle Premium-Deckdesigns'),
    t(en: 'No ads—ever', es: 'Sin anuncios, nunca', fr: 'Aucune publicité', pt: 'Sem anúncios', tr: 'Asla reklam yok', it: 'Mai pubblicità', de: 'Nie Werbung'),
  ];

  Widget _notice(String text) => Container(padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 11), decoration: BoxDecoration(color: MysticColors.gold.withValues(alpha: .09), borderRadius: BorderRadius.circular(16), border: Border.all(color: MysticColors.gold.withValues(alpha: .28))), child: Row(children: [const Icon(Icons.language, size: 18, color: MysticColors.gold), const SizedBox(width: 10), Expanded(child: Text(text, style: const TextStyle(fontFamily: 'Arial', color: MysticColors.lavender, fontSize: 10, fontWeight: FontWeight.w800)))]));

  Widget _plan(int index, String title, String price, String subtitle, {String? badge}) {
    final active = plan == index;
    return InkWell(onTap: () => setState(() => plan = index), borderRadius: BorderRadius.circular(18), child: Stack(clipBehavior: Clip.none, children: [Container(padding: const EdgeInsets.fromLTRB(8, 17, 8, 12), decoration: BoxDecoration(color: active ? MysticColors.violet.withValues(alpha: .35) : Colors.white.withValues(alpha: .04), borderRadius: BorderRadius.circular(18), border: Border.all(color: active ? MysticColors.gold : Colors.white12, width: active ? 2 : 1)), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [Text(title, textAlign: TextAlign.center, style: const TextStyle(fontFamily: 'Arial', fontWeight: FontWeight.bold, fontSize: 10)), const SizedBox(height: 7), Text(price, style: TextStyle(fontFamily: 'Arial', fontSize: index == 2 ? 18 : 16, fontWeight: FontWeight.bold, color: MysticColors.gold)), const SizedBox(height: 3), Text(subtitle, textAlign: TextAlign.center, style: const TextStyle(fontFamily: 'Arial', fontSize: 8, color: MysticColors.muted))])), if (badge != null) Positioned(top: -7, left: 5, right: 5, child: Container(padding: const EdgeInsets.symmetric(vertical: 4), decoration: BoxDecoration(color: MysticColors.gold, borderRadius: BorderRadius.circular(12)), child: Text(badge, textAlign: TextAlign.center, style: const TextStyle(fontFamily: 'Arial', color: MysticColors.ink, fontSize: 6.5, fontWeight: FontWeight.w900))))]));
  }

  void _beginPurchase() => showModalBottomSheet<void>(context: context, backgroundColor: const Color(0xFF171128), shape: const RoundedRectangleBorder(borderRadius: BorderRadius.vertical(top: Radius.circular(26))), builder: (sheetContext) => SafeArea(child: Padding(padding: const EdgeInsets.fromLTRB(22, 16, 22, 28), child: Column(mainAxisSize: MainAxisSize.min, children: [const Icon(Icons.verified_user_outlined, color: MysticColors.gold, size: 40), const SizedBox(height: 12), Text(t(en: 'Store checkout is being connected.', es: 'La conexión con la tienda está en preparación.', fr: 'La connexion à la boutique est en préparation.', pt: 'A conexão com a loja está sendo preparada.', tr: 'Mağaza ödeme bağlantısı hazırlanıyor.', it: 'Il collegamento allo store è in preparazione.', de: 'Die Store-Anbindung wird vorbereitet.'), textAlign: TextAlign.center, style: Theme.of(context).textTheme.titleLarge), const SizedBox(height: 9), Text(t(en: 'No subscription is activated and no payment is collected in this release.', es: 'Esta versión no activa suscripciones ni cobra pagos.', fr: 'Cette version n’active aucun abonnement et ne prélève aucun paiement.', pt: 'Esta versão não ativa assinaturas nem cobra pagamentos.', tr: 'Bu sürüm abonelik etkinleştirmez ve ödeme almaz.', it: 'Questa versione non attiva abbonamenti e non raccoglie pagamenti.', de: 'Diese Version aktiviert kein Abonnement und erhebt keine Zahlung.'), textAlign: TextAlign.center, style: Theme.of(context).textTheme.bodyMedium), const SizedBox(height: 18), GoldButton(label: t(en: 'Continue with free access', es: 'Continuar con acceso gratuito', fr: 'Continuer avec l’accès gratuit', pt: 'Continuar com acesso gratuito', tr: 'Ücretsiz erişimle devam et', it: 'Continua con accesso gratuito', de: 'Mit kostenlosem Zugang fortfahren'), onPressed: () => Navigator.pop(sheetContext))]))));

  void _restore() => ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(t(en: 'Restore Purchases activates with native store billing.', es: 'Restaurar compras se activará con la facturación nativa.', fr: 'La restauration sera disponible avec la facturation native.', pt: 'A restauração será ativada com a cobrança nativa.', tr: 'Satın alımları geri yükleme yerel mağaza ödemesiyle etkinleşecek.', it: 'Il ripristino sarà disponibile con la fatturazione nativa.', de: 'Käufe wiederherstellen wird mit nativer Store-Abrechnung aktiviert.'))));

  void _legal(bool privacy) => showDialog<void>(context: context, builder: (dialogContext) => AlertDialog(title: Text(privacy ? t(en: 'Privacy', es: 'Privacidad', fr: 'Confidentialité', pt: 'Privacidade', tr: 'Gizlilik', it: 'Privacy', de: 'Datenschutz') : t(en: 'Terms', es: 'Términos', fr: 'Conditions', pt: 'Termos', tr: 'Koşullar', it: 'Termini', de: 'Bedingungen')), content: Text(t(en: 'Mystic Tarot is a reflection and entertainment product. This release stores data locally and does not process payments.', es: 'Mystic Tarot es un producto de reflexión y entretenimiento. Esta versión guarda datos localmente y no procesa pagos.', fr: 'Mystic Tarot est un produit de réflexion et de divertissement. Cette version stocke les données localement et ne traite aucun paiement.', pt: 'Mystic Tarot é um produto de reflexão e entretenimento. Esta versão armazena dados localmente e não processa pagamentos.', tr: 'Mystic Tarot kişisel düşünme ve eğlence ürünüdür. Bu sürüm verileri cihazda saklar ve ödeme işlemez.', it: 'Mystic Tarot è un prodotto di riflessione e intrattenimento. Questa versione salva i dati localmente e non elabora pagamenti.', de: 'Mystic Tarot ist ein Reflexions- und Unterhaltungsprodukt. Diese Version speichert Daten lokal und verarbeitet keine Zahlungen.')), actions: [TextButton(onPressed: () => Navigator.pop(dialogContext), child: Text(t(en: 'Close', es: 'Cerrar', fr: 'Fermer', pt: 'Fechar', tr: 'Kapat', it: 'Chiudi', de: 'Schließen')))]));
}
