class MysticTextCatalog {
  MysticTextCatalog._();

  static const Set<String> launchLanguageCodes = <String>{'ES', 'PT-BR'};

  static bool hasTranslation(String languageCode, String english) {
    final exact = switch (languageCode) {
      'ES' => _spanish.containsKey(english),
      'PT-BR' => _portugueseBrazil.containsKey(english),
      _ => false,
    };
    if (exact) return true;
    final templates = switch (languageCode) {
      'ES' => _spanishTemplates,
      'PT-BR' => _portugueseBrazilTemplates,
      _ => const <_MysticTemplate>[],
    };
    return templates.any((item) => item.source == english);
  }

  static int exactTranslationCount(String languageCode) => switch (languageCode) {
    'ES' => _spanish.length,
    'PT-BR' => _portugueseBrazil.length,
    _ => 0,
  };

  static int templateTranslationCount(String languageCode) => switch (languageCode) {
    'ES' => _spanishTemplates.length,
    'PT-BR' => _portugueseBrazilTemplates.length,
    _ => 0,
  };

  static String translate(String languageCode, String english) {
    final exact = switch (languageCode) {
      'ES' => _spanish[english],
      'PT-BR' => _portugueseBrazil[english],
      _ => null,
    };
    if (exact != null) return exact;
    final templates = switch (languageCode) {
      'ES' => _spanishTemplates,
      'PT-BR' => _portugueseBrazilTemplates,
      _ => const <_MysticTemplate>[],
    };
    for (final template in templates) {
      final translated = template.apply(english, languageCode);
      if (translated != null) return translated;
    }
    return english;
  }

  static String _translateCaptured(String languageCode, String value) {
    final direct = switch (languageCode) {
      'ES' => _spanish[value],
      'PT-BR' => _portugueseBrazil[value],
      _ => null,
    };
    return direct ?? value;
  }

  static const Map<String, String> _spanish = <String, String>{
    'LIVING JOURNAL': 'DIARIO VIVO',
    'Your story remembers.': 'Tu historia te recuerda.',
    'Timeline': 'Cronología',
    'Insights': 'Perspectivas',
    'Map': 'Mapa',
    'Search': 'Buscar',
    'reversed': 'invertida',
    'upright': 'derecha',
    'Total readings': 'Lecturas totales',
    'Last 30 days': 'Últimos 30 días',
    'Cards returning to you': 'Cartas que vuelven a ti',
    'Emotional weather': 'Clima emocional',
    'Unlock your full pattern map': 'Desbloquea tu mapa completo de patrones',
    'Explore Premium': 'Explorar Premium',
    'Anxious': 'Ansioso',
    'Hopeful': 'Esperanzado',
    'Grounded': 'Centrado',
    'Curious': 'Curioso',
    'Uncertain': 'Incierto',
    'Your journal is waiting.': 'Tu diario te espera.',
    'Your reading timeline': 'Tu cronología de lecturas',
    'Every saved reading, in context': 'Cada lectura guardada, en su contexto',
    'Recurring patterns': 'Patrones recurrentes',
    'Cards and emotions that return': 'Cartas y emociones que regresan',
    'Private memory map': 'Mapa privado de recuerdos',
    'Connections only you can see': 'Conexiones que solo tú puedes ver',
    'Create my first memory': 'Crear mi primer recuerdo',
    'Try again': 'Intentar de nuevo',
    'Journeys': 'Viajes',
    'Destiny path': 'Camino del destino',
    'Create journey': 'Crear viaje',
    'New journey': 'Nuevo viaje',
    'Entries': 'Entradas',
    'Days': 'Días',
    'Reflected': 'Reflexionado',
    'Create a journey': 'Crear un viaje',
    'Journey name': 'Nombre del viaje',
    'A name is required.': 'Se necesita un nombre.',
    'Intention': 'Intención',
    'Life area': 'Área de vida',
    'Begin journey': 'Comenzar viaje',
    'Resume': 'Continuar',
    'Pause': 'Pausar',
    'Complete': 'Completar',
    'Archive': 'Archivar',
    'Active days': 'Días activos',
    'Start a reading': 'Iniciar una lectura',
    'Add reflection': 'Añadir reflexión',
    'Reflection': 'Reflexión',
    'Add a reflection': 'Añadir una reflexión',
    'Mood (optional)': 'Estado de ánimo (opcional)',
    'Save reflection': 'Guardar reflexión',
    'Name what matters': 'Nombra lo que importa',
    'Love, work, healing or your own path': 'Amor, trabajo, sanación o tu propio camino',
    'Connect your readings': 'Conecta tus lecturas',
    'Watch one question evolve over time': 'Observa cómo evoluciona una pregunta con el tiempo',
    'See your turning points': 'Descubre tus puntos de inflexión',
    'Mystic reveals the pattern behind your choices': 'Mystic revela el patrón detrás de tus decisiones',
    'Create first journey': 'Crear el primer viaje',
    'Relationship': 'Relación',
    'Career': 'Carrera',
    'Wellbeing': 'Bienestar',
    'Education': 'Educación',
    'Creativity': 'Creatividad',
    'Confidence': 'Confianza',
    'Personal': 'Personal',
    'Active': 'Activo',
    'Paused': 'En pausa',
    'Completed': 'Completado',
    'Archived': 'Archivado',
    'LIVING FATE MAP': 'MAPA VIVO DEL DESTINO',
    'Your story changes with every return.': 'Tu historia cambia cada vez que regresas.',
    'ENTER MY PATH': 'ENTRAR EN MI CAMINO',
    'My Living Path': 'Mi camino vivo',
    'Fate Map': 'Mapa del destino',
    '22 Days': '22 días',
    'YOUR LIVING SIGNALS': 'TUS SEÑALES VIVAS',
    'Your map is built from patterns—not predictions.': 'Tu mapa se construye con patrones, no con predicciones.',
    'Two saved readings awaken your first connection.': 'Dos lecturas guardadas despiertan tu primera conexión.',
    'What your path is saying': 'Lo que dice tu camino',
    'RECURRING SYMBOL': 'SÍMBOLO RECURRENTE',
    'No repeated card yet': 'Aún no hay ninguna carta repetida',
    'INNER WEATHER': 'CLIMA INTERIOR',
    'Waiting for your first reading': 'Esperando tu primera lectura',
    'ACTIVE LIFE AREA': 'ÁREA DE VIDA ACTIVA',
    'Begin with one honest reading. Mystic will connect the cards, emotions, and actions that return.': 'Empieza con una lectura sincera. Mystic conectará las cartas, emociones y acciones que regresen.',
    'Create my first signal': 'Crear mi primera señal',
    'The Major Arcana Journey': 'El viaje de los Arcanos Mayores',
    'One chapter a day. No punishment for missing a day.': 'Un capítulo al día. No hay castigo por perder un día.',
    'TODAY’S FOCUS': 'ENFOQUE DE HOY',
    'REAL-WORLD RITUAL': 'RITUAL EN LA VIDA REAL',
    'REFLECTION': 'REFLEXIÓN',
    'Write one honest sentence…': 'Escribe una frase sincera…',
    'Today’s chapter is sealed': 'El capítulo de hoy está sellado',
    'Return tomorrow. Integration matters more than speed.': 'Vuelve mañana. Integrar importa más que avanzar rápido.',
    'Your sealed chapters': 'Tus capítulos sellados',
    'The first cycle is complete.': 'El primer ciclo está completo.',
    'Your 22 reflections now live inside your Fate Map. The next cycle will compare who you were with who you are becoming.': 'Tus 22 reflexiones ahora viven dentro de tu Mapa del Destino. El próximo ciclo comparará quién eras con quien estás llegando a ser.',
    'CYCLE COMPLETE': 'CICLO COMPLETO',
    'Mystic Story Studio': 'Mystic Story Studio',
    'A cinematic story card, ready to share.': 'Una tarjeta de historia cinematográfica, lista para compartir.',
    'Midnight': 'Medianoche',
    'Solar': 'Solar',
    'Blood Moon': 'Luna de Sangre',
    'Preparing…': 'Preparando…',
    'Share my story card': 'Compartir mi tarjeta de historia',
    'Exports a private image. Your question and journal notes are never included.': 'Exporta una imagen privada. Tu pregunta y las notas de tu diario nunca se incluyen.',
    'Sharing was unavailable, so your reading was copied.': 'No se pudo compartir, así que tu lectura se copió.',
    'A REFLECTION, NOT A FIXED PREDICTION': 'UNA REFLEXIÓN, NO UNA PREDICCIÓN FIJA',
    'Clarity': 'Claridad',
    'Read': 'Leer',
    'Path': 'Camino',
    'Journal': 'Diario',
    'You': 'Tú',
    'Close discovery': 'Cerrar descubrimiento',
    '✦  NEW ARCANA AWAKENED': '✦  NUEVO ARCANO DESPERTADO',
    'Reveal next card': 'Revelar la siguiente carta',
    'Add to Arcana Vault': 'Añadir a la Bóveda de Arcanos',
    'Legendary': 'Legendaria',
    'Epic': 'Épica',
    'Rare': 'Rara',
    'Common': 'Común',
    'Your cards are waiting': 'Tus cartas te esperan',
    'Choose a reading': 'Elige una lectura',
    'Explore every reading': 'Explorar todas las lecturas',
    'Mystic Plus readings': 'Lecturas de Mystic Plus',
    'High-depth spreads built for the questions people return to most.': 'Tiradas profundas creadas para las preguntas a las que más volvemos.',
    'Your path remembers': 'Tu camino recuerda',
    'Good morning': 'Buenos días',
    'Good afternoon': 'Buenas tardes',
    'Good evening': 'Buenas noches',
    'Reading library': 'Biblioteca de lecturas',
    'Choose the question that needs your attention now.': 'Elige la pregunta que necesita tu atención ahora.',
    'Mystic remembers your pattern': 'Mystic recuerda tu patrón',
    'Save two readings and Mystic will begin connecting recurring cards, emotions, and choices into a private pattern map.': 'Guarda dos lecturas y Mystic empezará a conectar cartas, emociones y decisiones recurrentes en un mapa privado de patrones.',
    'Love': 'Amor',
    'Purpose': 'Propósito',
    'Healing': 'Sanación',
    'Unlimited deep readings active': 'Lecturas profundas ilimitadas activas',
    'Free deep readings used': 'Lecturas profundas gratuitas agotadas',
    'Your verified Mystic Plus entitlement is active.': 'Tu acceso verificado a Mystic Plus está activo.',
    'Unlock unlimited readings with Mystic Plus.': 'Desbloquea lecturas ilimitadas con Mystic Plus.',
    'Your Daily Guidance remains free every day.': 'Tu Guía Diaria seguirá siendo gratuita cada día.',
    'PLUS ACTIVE': 'PLUS ACTIVO',
    'VIEW PLUS': 'VER PLUS',
    'TONIGHT’S MYSTIC PULSE': 'PULSO MYSTIC DE ESTA NOCHE',
    'Release urgency. Choose the honest next step.': 'Suelta la urgencia. Elige el siguiente paso más honesto.',
    '2 MIN': '2 MIN',
    'YOUR DAILY PORTAL': 'TU PORTAL DIARIO',
    'Reveal what\nneeds you today': 'Descubre qué\\nte necesita hoy',
    'DAILY SOUL QUEST': 'MISIÓN DIARIA DEL ALMA',
    'Today’s relic is yours.': 'La reliquia de hoy es tuya.',
    'Your chest is ready to open.': 'Tu cofre está listo para abrirse.',
    'Complete both steps • +40 XP': 'Completa ambos pasos • +40 XP',
    'Daily card': 'Carta diaria',
    'One ritual': 'Un ritual',
    'Close reward': 'Cerrar recompensa',
    'SOUL CHEST OPENED': 'COFRE DEL ALMA ABIERTO',
    'Moon Shard added to your constellation.': 'Fragmento Lunar añadido a tu constelación.',
    'Continue my path': 'Continuar mi camino',
    'Breathe slowly. Hold your question in mind, then choose the cards that call to you.': 'Respira despacio. Mantén tu pregunta en mente y elige las cartas que te llamen.',
    'Write your question (optional)': 'Escribe tu pregunta (opcional)',
    'HOW DO YOU FEEL RIGHT NOW?': '¿CÓMO TE SIENTES AHORA?',
    'CHOOSE YOUR CARDS': 'ELIGE TUS CARTAS',
    'Trust the first pull': 'Confía en la primera elección',
    'Seal my selection': 'Sellar mi selección',
    'Your reading': 'Tu lectura',
    'Share reading': 'Compartir lectura',
    'Take what resonates. Tarot is a mirror for reflection—not a fixed prediction.': 'Quédate con lo que resuene. El tarot es un espejo para reflexionar, no una predicción fija.',
    '✦  YOUR GUIDANCE': '✦  TU GUÍA',
    'MYSTIC MIRROR • 24H LOOP': 'ESPEJO MYSTIC • CICLO DE 24 H',
    'Your aligned action': 'Tu acción alineada',
    'Tomorrow, Mystic will ask what actually changed. Your answer becomes part of your personal pattern map.': 'Mañana Mystic te preguntará qué cambió de verdad. Tu respuesta pasará a formar parte de tu mapa personal de patrones.',
    'Saved to your journal': 'Guardado en tu diario',
    'Save this reading': 'Guardar esta lectura',
    'Return home': 'Volver al inicio',
    'MESSAGE': 'MENSAJE',
    'What surrounds you': 'Lo que te rodea',
    'What asks for attention': 'Lo que pide atención',
    'Your next aligned step': 'Tu siguiente paso alineado',
    ' — Reversed': ' — Invertida',
    'A hopeful path is becoming visible.': 'Empieza a hacerse visible un camino esperanzador.',
    'The truth arrives when you slow down.': 'La verdad llega cuando bajas el ritmo.',
    '◉  ORACLE MEMORY': '◉  MEMORIA DEL ORÁCULO',
    'ASK THE ORACLE': 'PREGUNTAR AL ORÁCULO',
    'UNLIMITED': 'ILIMITADO',
    'CONTINUE PLUS': 'CONTINUAR CON PLUS',
    '1 FREE': '1 GRATIS',
    'Ask unlimited personal follow-ups whenever you return to this reading.': 'Haz preguntas personales ilimitadas cada vez que vuelvas a esta lectura.',
    'Your free answer is complete. Continue the dialogue with Mystic Plus.': 'Tu respuesta gratuita está completa. Continúa el diálogo con Mystic Plus.',
    'Go beyond the first interpretation with one personal follow-up question.': 'Ve más allá de la primera interpretación con una pregunta personal de seguimiento.',
    'Delay one fear-based decision. Write down what is known, what is assumed, and what can wait until tomorrow.': 'Pospón una decisión basada en el miedo. Anota qué sabes, qué supones y qué puede esperar hasta mañana.',
    'Turn hope into evidence: take one small action that your future self can continue tomorrow.': 'Convierte la esperanza en evidencia: da un pequeño paso que tu yo futuro pueda continuar mañana.',
    'Use today’s steadiness to complete one conversation or task you have been leaving open.': 'Usa la estabilidad de hoy para completar una conversación o tarea que hayas dejado abierta.',
    'Ask one honest question without trying to control the answer.': 'Haz una pregunta sincera sin intentar controlar la respuesta.',
    'Choose the smallest reversible step. Clarity often appears after movement, not before it.': 'Elige el paso reversible más pequeño. La claridad suele aparecer después de moverte, no antes.',
    'REVEAL RITUAL': 'RITUAL DE REVELACIÓN',
    'INTENTION': 'INTENCIÓN',
    'SELECTION': 'SELECCIÓN',
    'REVEAL': 'REVELACIÓN',
    'Your cards are\nwaiting beneath the veil.': 'Tus cartas te esperan\\nbajo el velo.',
    'Opening the veil…': 'Abriendo el velo…',
    'Open the seal': 'Abrir el sello',
    'Take what resonates. The cards offer reflection, not certainty.': 'Quédate con lo que resuene. Las cartas ofrecen reflexión, no certeza.',
    'Oracle Dialogue': 'Diálogo con el Oráculo',
    'The Oracle is listening.': 'El Oráculo está escuchando.',
    'Reversed': 'Invertida',
    'CHOOSE A FOLLOW-UP': 'ELIGE UNA PREGUNTA DE SEGUIMIENTO',
    'Or ask in your own words…': 'O pregunta con tus propias palabras…',
    'Ask the Oracle': 'Preguntar al Oráculo',
    'Ask my free question': 'Hacer mi pregunta gratuita',
    'The Oracle is connecting your symbols…': 'El Oráculo está conectando tus símbolos…',
    'Continue the conversation': 'Continuar la conversación',
    'Ask unlimited follow-ups, revisit saved conversations, and unlock every deep spread with Mystic Plus.': 'Haz preguntas ilimitadas, vuelve a conversaciones guardadas y desbloquea todas las tiradas profundas con Mystic Plus.',
    'Unlock Oracle Dialogue': 'Desbloquear el Diálogo con el Oráculo',
    'Ask another question': 'Hacer otra pregunta',
    'Return to my reading': 'Volver a mi lectura',
    'Your card is finding its voice…': 'Tu carta está encontrando su voz…',
    'The cards are forming a pattern…': 'Las cartas están formando un patrón…',
    'Stay with your first feeling. The full interpretation appears after the final card turns.': 'Quédate con tu primera sensación. La interpretación completa aparecerá después de que gire la última carta.',
    'Your Mystic Path': 'Tu Camino Mystic',
    'Your inner world becomes visible as you practice.': 'Tu mundo interior se hace visible con la práctica.',
    'INNER CONSTELLATION': 'CONSTELACIÓN INTERIOR',
    'Today’s rituals': 'Rituales de hoy',
    'Small actions turn insight into change. Each ritual grants +15 XP.': 'Las pequeñas acciones convierten la comprensión en cambio. Cada ritual otorga +15 XP.',
    '60-second reset': 'Reinicio de 60 segundos',
    'Breathe in for four, out for six.': 'Inhala durante cuatro y exhala durante seis.',
    'Name the truth': 'Nombra la verdad',
    'Write one sentence you have been avoiding.': 'Escribe una frase que hayas estado evitando.',
    'Aligned action': 'Acción alineada',
    'Take the smallest reversible next step.': 'Da el siguiente paso reversible más pequeño.',
    'Mystic rewards': 'Recompensas Mystic',
    'Your practice unlocks cosmetic relics—never better answers.': 'Tu práctica desbloquea reliquias cosméticas, nunca respuestas “mejores”.',
    'Moon Dust': 'Polvo Lunar',
    'Oracle Flame': 'Llama del Oráculo',
    'Astral Crown': 'Corona Astral',
    'Return tomorrow to keep your constellation alive.': 'Vuelve mañana para mantener viva tu constelación.',
    'CLAIMED': 'RECLAMADO',
    'CLAIM': 'RECLAMAR',
    'Ritual complete • +15 XP': 'Ritual completado • +15 XP',
    'ARCANA VAULT': 'BÓVEDA DE ARCANOS',
    'Every reading can awaken a card.': 'Cada lectura puede despertar una carta.',
    'The entire deck has answered you.': 'Toda la baraja te ha respondido.',
    'Undiscovered': 'Sin descubrir',
    'Your Arcana Vault': 'Tu Bóveda de Arcanos',
    'Locked': 'Bloqueada',
    'UNDISCOVERED': 'SIN DESCUBRIR',
    'LIGHT': 'LUZ',
    'SHADOW': 'SOMBRA',
    'ALIGNED ACTION': 'ACCIÓN ALINEADA',
    'YOUR WEEKLY MYSTIC WRAPPED': 'TU RESUMEN MYSTIC SEMANAL',
    'Your story is waiting for its first signal.': 'Tu historia espera su primera señal.',
    '✦  MYSTIC WRAPPED': '✦  RESUMEN MYSTIC',
    'Your first pattern begins with one honest reading.': 'Tu primer patrón comienza con una lectura sincera.',
    'REFLECTIONS': 'REFLEXIONES',
    'No card yet': 'Aún no hay ninguna carta',
    'REPEATING CARD': 'CARTA RECURRENTE',
    'Complete a reading and return here to watch your emotional patterns become visible.': 'Completa una lectura y vuelve aquí para ver cómo se hacen visibles tus patrones emocionales.',
    'Begin my first reading': 'Comenzar mi primera lectura',
    'Keep building my pattern': 'Seguir construyendo mi patrón',
    'First Signal': 'Primera Señal',
    'Save 1 reading': 'Guardar 1 lectura',
    'Flame Keeper': 'Guardián de la Llama',
    'Reach a 3-day streak': 'Alcanza una racha de 3 días',
    'Arcana Seeker': 'Buscador de Arcanos',
    'Awaken 10 cards': 'Despierta 10 cartas',
    'Relic Keeper': 'Guardián de Reliquias',
    'Claim an XP relic': 'Reclama una reliquia de XP',
    'Reading preferences': 'Preferencias de lectura',
    'Privacy & data': 'Privacidad y datos',
    'Help and support': 'Ayuda y soporte',
    'Your space': 'Tu espacio',
    'LEVEL': 'NIVEL',
    'day streak': 'días de racha',
    'readings': 'lecturas',
    'arcana': 'arcanos',
    'Mystic achievements': 'Logros Mystic',
    'Your practice leaves permanent marks on your path.': 'Tu práctica deja huellas permanentes en tu camino.',
    'Your tarot deck': 'Tu baraja de tarot',
    'Choose the visual energy that follows every reading.': 'Elige la energía visual que acompañará cada lectura.',
    'Mystic Plus active': 'Mystic Plus activo',
    'Unlock Mystic Plus': 'Desbloquear Mystic Plus',
    'View plan and manage subscription': 'Ver el plan y gestionar la suscripción',
    'Go deeper with unlimited readings': 'Profundiza con lecturas ilimitadas',
    'Soul profile': 'Perfil del alma',
    'Language': 'Idioma',
    'Choose language': 'Elegir idioma',
    'Mystic is fully available in English, Turkish, Spanish, and Brazilian Portuguese.': 'Mystic está disponible por completo en inglés, turco, español y portugués de Brasil.',
    'Astral Sage': 'Sabio Astral',
    'Mystic Oracle': 'Oráculo Mystic',
    'Mystic Initiate': 'Iniciado Mystic',
    'Love path': 'Camino del amor',
    'Purpose path': 'Camino del propósito',
    'Healing path': 'Camino de sanación',
    'Clarity path': 'Camino de claridad',
    'UNLOCKED': 'DESBLOQUEADO',
    'ACTIVE DECK': 'BARAJA ACTIVA',
    'Solar Gold': 'Oro Solar',
    'Make Mystic yours': 'Haz que Mystic sea tuyo',
    'Your name and intention shape the language, memory, and guidance around every reading.': 'Tu nombre y tu intención dan forma al lenguaje, la memoria y la guía de cada lectura.',
    'Your name': 'Tu nombre',
    'YOUR CURRENT PATH': 'TU CAMINO ACTUAL',
    'Save my soul profile': 'Guardar mi perfil del alma',
    'Stored privately on this device.': 'Guardado de forma privada en este dispositivo.',
    'PLUS PREVIEW': 'VISTA PREVIA DE PLUS',
    'The first signal is forming…': 'La primera señal se está formando…',
    'YOUR FIRST SIGNAL': 'TU PRIMERA SEÑAL',
    'Reversed energy': 'Energía invertida',
    'Upright energy': 'Energía al derecho',
    'The rest of your spread': 'El resto de tu tirada',
    'Included with Mystic Plus • Cancel anytime': 'Incluido con Mystic Plus • Cancela cuando quieras',
    'Shape every reading': 'Da forma a cada lectura',
    'Allow reversed cards': 'Permitir cartas invertidas',
    'Ritual sound effects': 'Efectos de sonido del ritual',
    'Reflection-first guidance': 'Guía centrada en la reflexión',
    'Your inner world stays yours': 'Tu mundo interior sigue siendo tuyo',
    'Export my journal': 'Exportar mi diario',
    'Delete all Mystic data': 'Eliminar todos los datos de Mystic',
    'Entertainment & reflection': 'Entretenimiento y reflexión',
    'We are here to help': 'Estamos aquí para ayudarte',
    'Does Mystic predict the future?': '¿Mystic predice el futuro?',
    'Can I cancel Mystic Plus?': '¿Puedo cancelar Mystic Plus?',
    'How do I restore a purchase?': '¿Cómo restauro una compra?',
    'Is my journal private?': '¿Mi diario es privado?',
    'Copy support link': 'Copiar enlace de soporte',
    'Support link copied.': 'Enlace de soporte copiado.',
    ' (Reversed)': ' (Invertida)',
    'Delete all Mystic data?': '¿Eliminar todos los datos de Mystic?',
    'Keep my data': 'Conservar mis datos',
    'Delete everything': 'Eliminar todo',
    'Your memory map is waiting.': 'Tu mapa de recuerdos te espera.',
    'Your patterns, connected.': 'Tus patrones, conectados.',
    'Memory Map': 'Mapa de Recuerdos',
    'Strongest connection': 'Conexión más fuerte',
    'Search by meaning': 'Buscar por significado',
    'No connected memory found yet.': 'Aún no se ha encontrado ningún recuerdo conectado.',
    'Daily': 'Diaria',
    'Money': 'Dinero',
    'Decision': 'Decisión',
    'Spirit': 'Espíritu',
    'Shadow': 'Sombra',
    'Future': 'Futuro',
    'Begin before certainty arrives': 'Empieza antes de que llegue la certeza',
    'Take one small step you can reverse.': 'Da un pequeño paso que puedas deshacer.',
    'What would I try if I did not need to look ready?': '¿Qué intentaría si no necesitara parecer preparado?',
    'Direct your available power': 'Dirige el poder que ya tienes',
    'Choose one tool and use it for fifteen focused minutes.': 'Elige una herramienta y úsala durante quince minutos de concentración.',
    'Where am I waiting for a resource I already have?': '¿Dónde estoy esperando un recurso que ya tengo?',
    'Listen beneath the noise': 'Escucha debajo del ruido',
    'Sit without input for three quiet minutes.': 'Permanece tres minutos en silencio, sin estímulos.',
    'What does my body know before my mind explains it?': '¿Qué sabe mi cuerpo antes de que mi mente lo explique?',
    'Nourish what should grow': 'Nutre lo que debe crecer',
    'Improve one condition around your creative work.': 'Mejora una condición alrededor de tu trabajo creativo.',
    'What becomes possible when I stop starving my own needs?': '¿Qué se vuelve posible cuando dejo de privarme de mis propias necesidades?',
    'Build a kind structure': 'Construye una estructura amable',
    'Create one boundary that makes tomorrow easier.': 'Crea un límite que haga mañana más fácil.',
    'Which rule protects me, and which one only controls me?': '¿Qué regla me protege y cuál solo me controla?',
    'Choose your living tradition': 'Elige tu tradición viva',
    'Keep one useful teaching and question one inherited rule.': 'Conserva una enseñanza útil y cuestiona una regla heredada.',
    'What deserves my respect rather than blind obedience?': '¿Qué merece mi respeto en lugar de una obediencia ciega?',
    'Align desire with values': 'Alinea el deseo con tus valores',
    'Name the value beneath one important choice.': 'Nombra el valor que hay debajo de una decisión importante.',
    'What choice lets me stay connected without leaving myself?': '¿Qué elección me permite seguir conectado sin abandonarme?',
    'Move with a named direction': 'Avanza con una dirección definida',
    'Write your destination before increasing your speed.': 'Escribe tu destino antes de aumentar la velocidad.',
    'Am I moving toward something or merely escaping?': '¿Me estoy acercando a algo o solo estoy escapando?',
    'Practice gentle courage': 'Practica un valor sereno',
    'Meet one difficult feeling without trying to defeat it.': 'Encuéntrate con una emoción difícil sin intentar vencerla.',
    'What changes when strength no longer means force?': '¿Qué cambia cuando la fuerza deja de significar imposición?',
    'Return with your own light': 'Regresa con tu propia luz',
    'Step away from input, then write one honest sentence.': 'Aléjate de los estímulos y después escribe una frase sincera.',
    'Which answer can only be heard in solitude?': '¿Qué respuesta solo puede escucharse en soledad?',
    'Work with the turning cycle': 'Trabaja con el ciclo que gira',
    'Release one expectation that belongs to yesterday.': 'Suelta una expectativa que pertenece a ayer.',
    'What opening appears when I stop demanding the old shape?': '¿Qué oportunidad aparece cuando dejo de exigir la forma antigua?',
    'Restore honest proportion': 'Recupera una proporción honesta',
    'Name your part without taking all the blame.': 'Reconoce tu parte sin cargar con toda la culpa.',
    'What decision would I respect if nobody applauded?': '¿Qué decisión respetaría aunque nadie aplaudiera?',
    'See from the opposite angle': 'Mira desde el ángulo opuesto',
    'Argue sincerely for the view you resist.': 'Defiende con sinceridad el punto de vista al que te resistes.',
    'What becomes visible when progress pauses?': '¿Qué se hace visible cuando el progreso se detiene?',
    'Release the completed form': 'Suelta la forma que ya terminó',
    'Remove one object, task, or promise that is already over.': 'Retira un objeto, una tarea o una promesa que ya haya terminado.',
    'Which identity can no longer carry me forward?': '¿Qué identidad ya no puede llevarme hacia adelante?',
    'Integrate instead of swinging': 'Integra en lugar de oscilar',
    'Make the next adjustment small enough to sustain.': 'Haz que el próximo ajuste sea lo bastante pequeño como para sostenerlo.',
    'Where would five percent be wiser than all or nothing?': '¿Dónde sería más sabio un cinco por ciento que todo o nada?',
    'Name the hidden bargain': 'Nombra el trato oculto',
    'Write the real cost of one familiar attachment.': 'Escribe el coste real de un apego conocido.',
    'What keeps choosing for me when I stop paying attention?': '¿Qué sigue eligiendo por mí cuando dejo de prestar atención?',
    'Protect truth through change': 'Protege la verdad durante el cambio',
    'Separate what is falling from what is genuinely valuable.': 'Separa lo que se está cayendo de lo que realmente tiene valor.',
    'What false structure am I exhausted from maintaining?': '¿Qué estructura falsa estoy agotado de mantener?',
    'Practice evidence of hope': 'Practica pruebas de esperanza',
    'Do one hopeful act that asks nothing from the outcome.': 'Haz un acto esperanzador que no le exija nada al resultado.',
    'What small act would make possibility feel safe again?': '¿Qué pequeño acto haría que la posibilidad volviera a sentirse segura?',
    'Wait for more light': 'Espera más luz',
    'Divide one fear into facts, assumptions, and unknowns.': 'Divide un miedo entre hechos, suposiciones y desconocidos.',
    'Where has uncertainty been disguised as certainty?': '¿Dónde se ha disfrazado la incertidumbre de certeza?',
    'Let joy be uncomplicated': 'Deja que la alegría sea sencilla',
    'Share one warm moment without performing it.': 'Comparte un momento cálido sin convertirlo en una actuación.',
    'What goodness am I making harder than it needs to be?': '¿Qué cosa buena estoy haciendo más difícil de lo necesario?',
    'Answer the deeper call': 'Responde a la llamada más profunda',
    'Write what the next version of you refuses to postpone.': 'Escribe lo que tu próxima versión se niega a seguir posponiendo.',
    'Who am I becoming when old shame is not in charge?': '¿En quién me estoy convirtiendo cuando la vieja vergüenza ya no manda?',
    'Honor completion': 'Honra lo que se completa',
    'Close one open loop and name what it taught you.': 'Cierra un ciclo abierto y nombra lo que te enseñó.',
    'What must be celebrated before the next chapter begins?': '¿Qué debe celebrarse antes de que empiece el siguiente capítulo?',
  };

  static const Map<String, String> _portugueseBrazil = <String, String>{
    'LIVING JOURNAL': 'DIÁRIO VIVO',
    'Your story remembers.': 'Sua história se lembra de você.',
    'Timeline': 'Linha do tempo',
    'Insights': 'Percepções',
    'Map': 'Mapa',
    'Search': 'Buscar',
    'reversed': 'invertida',
    'upright': 'em pé',
    'Total readings': 'Total de leituras',
    'Last 30 days': 'Últimos 30 dias',
    'Cards returning to you': 'Cartas que voltam para você',
    'Emotional weather': 'Clima emocional',
    'Unlock your full pattern map': 'Desbloqueie seu mapa completo de padrões',
    'Explore Premium': 'Explorar Premium',
    'Anxious': 'Ansioso',
    'Hopeful': 'Esperançoso',
    'Grounded': 'Centrado',
    'Curious': 'Curioso',
    'Uncertain': 'Incerto',
    'Your journal is waiting.': 'Seu diário está esperando.',
    'Your reading timeline': 'Sua linha do tempo de leituras',
    'Every saved reading, in context': 'Cada leitura salva, em seu contexto',
    'Recurring patterns': 'Padrões recorrentes',
    'Cards and emotions that return': 'Cartas e emoções que retornam',
    'Private memory map': 'Mapa privado de memórias',
    'Connections only you can see': 'Conexões que só você pode ver',
    'Create my first memory': 'Criar minha primeira memória',
    'Try again': 'Tentar novamente',
    'Journeys': 'Jornadas',
    'Destiny path': 'Caminho do destino',
    'Create journey': 'Criar jornada',
    'New journey': 'Nova jornada',
    'Entries': 'Registros',
    'Days': 'Dias',
    'Reflected': 'Refletido',
    'Create a journey': 'Criar uma jornada',
    'Journey name': 'Nome da jornada',
    'A name is required.': 'É necessário informar um nome.',
    'Intention': 'Intenção',
    'Life area': 'Área da vida',
    'Begin journey': 'Iniciar jornada',
    'Resume': 'Continuar',
    'Pause': 'Pausar',
    'Complete': 'Concluir',
    'Archive': 'Arquivar',
    'Active days': 'Dias ativos',
    'Start a reading': 'Iniciar uma leitura',
    'Add reflection': 'Adicionar reflexão',
    'Reflection': 'Reflexão',
    'Add a reflection': 'Adicionar uma reflexão',
    'Mood (optional)': 'Humor (opcional)',
    'Save reflection': 'Salvar reflexão',
    'Name what matters': 'Dê nome ao que importa',
    'Love, work, healing or your own path': 'Amor, trabalho, cura ou seu próprio caminho',
    'Connect your readings': 'Conecte suas leituras',
    'Watch one question evolve over time': 'Observe uma pergunta evoluir com o tempo',
    'See your turning points': 'Veja seus pontos de virada',
    'Mystic reveals the pattern behind your choices': 'Mystic revela o padrão por trás das suas escolhas',
    'Create first journey': 'Criar a primeira jornada',
    'Relationship': 'Relacionamento',
    'Career': 'Carreira',
    'Wellbeing': 'Bem-estar',
    'Education': 'Educação',
    'Creativity': 'Criatividade',
    'Confidence': 'Confiança',
    'Personal': 'Pessoal',
    'Active': 'Ativa',
    'Paused': 'Pausada',
    'Completed': 'Concluída',
    'Archived': 'Arquivada',
    'LIVING FATE MAP': 'MAPA VIVO DO DESTINO',
    'Your story changes with every return.': 'Sua história muda a cada retorno.',
    'ENTER MY PATH': 'ENTRAR NO MEU CAMINHO',
    'My Living Path': 'Meu Caminho Vivo',
    'Fate Map': 'Mapa do Destino',
    '22 Days': '22 dias',
    'YOUR LIVING SIGNALS': 'SEUS SINAIS VIVOS',
    'Your map is built from patterns—not predictions.': 'Seu mapa é construído com padrões, não previsões.',
    'Two saved readings awaken your first connection.': 'Duas leituras salvas despertam sua primeira conexão.',
    'What your path is saying': 'O que seu caminho está dizendo',
    'RECURRING SYMBOL': 'SÍMBOLO RECORRENTE',
    'No repeated card yet': 'Ainda não há nenhuma carta repetida',
    'INNER WEATHER': 'CLIMA INTERIOR',
    'Waiting for your first reading': 'Aguardando sua primeira leitura',
    'ACTIVE LIFE AREA': 'ÁREA DA VIDA ATIVA',
    'Begin with one honest reading. Mystic will connect the cards, emotions, and actions that return.': 'Comece com uma leitura sincera. Mystic conectará as cartas, emoções e ações que retornarem.',
    'Create my first signal': 'Criar meu primeiro sinal',
    'The Major Arcana Journey': 'A Jornada dos Arcanos Maiores',
    'One chapter a day. No punishment for missing a day.': 'Um capítulo por dia. Sem punição por perder um dia.',
    'TODAY’S FOCUS': 'FOCO DE HOJE',
    'REAL-WORLD RITUAL': 'RITUAL NA VIDA REAL',
    'REFLECTION': 'REFLEXÃO',
    'Write one honest sentence…': 'Escreva uma frase sincera…',
    'Today’s chapter is sealed': 'O capítulo de hoje está selado',
    'Return tomorrow. Integration matters more than speed.': 'Volte amanhã. Integrar importa mais do que avançar rápido.',
    'Your sealed chapters': 'Seus capítulos selados',
    'The first cycle is complete.': 'O primeiro ciclo está completo.',
    'Your 22 reflections now live inside your Fate Map. The next cycle will compare who you were with who you are becoming.': 'Suas 22 reflexões agora vivem dentro do seu Mapa do Destino. O próximo ciclo comparará quem você era com quem está se tornando.',
    'CYCLE COMPLETE': 'CICLO COMPLETO',
    'Mystic Story Studio': 'Mystic Story Studio',
    'A cinematic story card, ready to share.': 'Um cartão de história cinematográfico, pronto para compartilhar.',
    'Midnight': 'Meia-noite',
    'Solar': 'Solar',
    'Blood Moon': 'Lua de Sangue',
    'Preparing…': 'Preparando…',
    'Share my story card': 'Compartilhar meu cartão de história',
    'Exports a private image. Your question and journal notes are never included.': 'Exporta uma imagem privada. Sua pergunta e as anotações do diário nunca são incluídas.',
    'Sharing was unavailable, so your reading was copied.': 'Não foi possível compartilhar, então sua leitura foi copiada.',
    'A REFLECTION, NOT A FIXED PREDICTION': 'UMA REFLEXÃO, NÃO UMA PREVISÃO FIXA',
    'Clarity': 'Clareza',
    'Read': 'Ler',
    'Path': 'Caminho',
    'Journal': 'Diário',
    'You': 'Você',
    'Close discovery': 'Fechar descoberta',
    '✦  NEW ARCANA AWAKENED': '✦  NOVO ARCANO DESPERTO',
    'Reveal next card': 'Revelar a próxima carta',
    'Add to Arcana Vault': 'Adicionar ao Cofre dos Arcanos',
    'Legendary': 'Lendária',
    'Epic': 'Épica',
    'Rare': 'Rara',
    'Common': 'Comum',
    'Your cards are waiting': 'Suas cartas estão esperando',
    'Choose a reading': 'Escolha uma leitura',
    'Explore every reading': 'Explorar todas as leituras',
    'Mystic Plus readings': 'Leituras do Mystic Plus',
    'High-depth spreads built for the questions people return to most.': 'Tiragens profundas criadas para as perguntas às quais as pessoas mais retornam.',
    'Your path remembers': 'Seu caminho se lembra',
    'Good morning': 'Bom dia',
    'Good afternoon': 'Boa tarde',
    'Good evening': 'Boa noite',
    'Reading library': 'Biblioteca de leituras',
    'Choose the question that needs your attention now.': 'Escolha a pergunta que precisa da sua atenção agora.',
    'Mystic remembers your pattern': 'Mystic se lembra do seu padrão',
    'Save two readings and Mystic will begin connecting recurring cards, emotions, and choices into a private pattern map.': 'Salve duas leituras e Mystic começará a conectar cartas, emoções e escolhas recorrentes em um mapa privado de padrões.',
    'Love': 'Amor',
    'Purpose': 'Propósito',
    'Healing': 'Cura',
    'Unlimited deep readings active': 'Leituras profundas ilimitadas ativas',
    'Free deep readings used': 'Leituras profundas gratuitas esgotadas',
    'Your verified Mystic Plus entitlement is active.': 'Seu acesso verificado ao Mystic Plus está ativo.',
    'Unlock unlimited readings with Mystic Plus.': 'Desbloqueie leituras ilimitadas com o Mystic Plus.',
    'Your Daily Guidance remains free every day.': 'Sua Orientação Diária continuará gratuita todos os dias.',
    'PLUS ACTIVE': 'PLUS ATIVO',
    'VIEW PLUS': 'VER PLUS',
    'TONIGHT’S MYSTIC PULSE': 'PULSO MYSTIC DESTA NOITE',
    'Release urgency. Choose the honest next step.': 'Solte a urgência. Escolha o próximo passo mais sincero.',
    '2 MIN': '2 MIN',
    'YOUR DAILY PORTAL': 'SEU PORTAL DIÁRIO',
    'Reveal what\nneeds you today': 'Descubra o que\\nprecisa de você hoje',
    'DAILY SOUL QUEST': 'MISSÃO DIÁRIA DA ALMA',
    'Today’s relic is yours.': 'A relíquia de hoje é sua.',
    'Your chest is ready to open.': 'Seu baú está pronto para ser aberto.',
    'Complete both steps • +40 XP': 'Conclua as duas etapas • +40 XP',
    'Daily card': 'Carta diária',
    'One ritual': 'Um ritual',
    'Close reward': 'Fechar recompensa',
    'SOUL CHEST OPENED': 'BAÚ DA ALMA ABERTO',
    'Moon Shard added to your constellation.': 'Fragmento Lunar adicionado à sua constelação.',
    'Continue my path': 'Continuar meu caminho',
    'Breathe slowly. Hold your question in mind, then choose the cards that call to you.': 'Respire devagar. Mantenha sua pergunta em mente e escolha as cartas que chamarem você.',
    'Write your question (optional)': 'Escreva sua pergunta (opcional)',
    'HOW DO YOU FEEL RIGHT NOW?': 'COMO VOCÊ SE SENTE AGORA?',
    'CHOOSE YOUR CARDS': 'ESCOLHA SUAS CARTAS',
    'Trust the first pull': 'Confie na primeira escolha',
    'Seal my selection': 'Selar minha seleção',
    'Your reading': 'Sua leitura',
    'Share reading': 'Compartilhar leitura',
    'Take what resonates. Tarot is a mirror for reflection—not a fixed prediction.': 'Leve o que fizer sentido. O tarô é um espelho para reflexão, não uma previsão fixa.',
    '✦  YOUR GUIDANCE': '✦  SUA ORIENTAÇÃO',
    'MYSTIC MIRROR • 24H LOOP': 'ESPELHO MYSTIC • CICLO DE 24 H',
    'Your aligned action': 'Sua ação alinhada',
    'Tomorrow, Mystic will ask what actually changed. Your answer becomes part of your personal pattern map.': 'Amanhã, Mystic perguntará o que realmente mudou. Sua resposta passará a fazer parte do seu mapa pessoal de padrões.',
    'Saved to your journal': 'Salvo no seu diário',
    'Save this reading': 'Salvar esta leitura',
    'Return home': 'Voltar ao início',
    'MESSAGE': 'MENSAGEM',
    'What surrounds you': 'O que está ao seu redor',
    'What asks for attention': 'O que pede atenção',
    'Your next aligned step': 'Seu próximo passo alinhado',
    ' — Reversed': ' — Invertida',
    'A hopeful path is becoming visible.': 'Um caminho esperançoso começa a ficar visível.',
    'The truth arrives when you slow down.': 'A verdade chega quando você desacelera.',
    '◉  ORACLE MEMORY': '◉  MEMÓRIA DO ORÁCULO',
    'ASK THE ORACLE': 'PERGUNTAR AO ORÁCULO',
    'UNLIMITED': 'ILIMITADO',
    'CONTINUE PLUS': 'CONTINUAR COM PLUS',
    '1 FREE': '1 GRÁTIS',
    'Ask unlimited personal follow-ups whenever you return to this reading.': 'Faça perguntas pessoais ilimitadas sempre que voltar a esta leitura.',
    'Your free answer is complete. Continue the dialogue with Mystic Plus.': 'Sua resposta gratuita está completa. Continue o diálogo com o Mystic Plus.',
    'Go beyond the first interpretation with one personal follow-up question.': 'Vá além da primeira interpretação com uma pergunta pessoal de acompanhamento.',
    'Delay one fear-based decision. Write down what is known, what is assumed, and what can wait until tomorrow.': 'Adie uma decisão baseada no medo. Anote o que é conhecido, o que é presumido e o que pode esperar até amanhã.',
    'Turn hope into evidence: take one small action that your future self can continue tomorrow.': 'Transforme esperança em evidência: dê um pequeno passo que seu eu do futuro possa continuar amanhã.',
    'Use today’s steadiness to complete one conversation or task you have been leaving open.': 'Use a estabilidade de hoje para concluir uma conversa ou tarefa que você deixou em aberto.',
    'Ask one honest question without trying to control the answer.': 'Faça uma pergunta sincera sem tentar controlar a resposta.',
    'Choose the smallest reversible step. Clarity often appears after movement, not before it.': 'Escolha o menor passo reversível. A clareza costuma aparecer depois do movimento, não antes.',
    'REVEAL RITUAL': 'RITUAL DE REVELAÇÃO',
    'INTENTION': 'INTENÇÃO',
    'SELECTION': 'SELEÇÃO',
    'REVEAL': 'REVELAÇÃO',
    'Your cards are\nwaiting beneath the veil.': 'Suas cartas estão esperando\\nsob o véu.',
    'Opening the veil…': 'Abrindo o véu…',
    'Open the seal': 'Abrir o selo',
    'Take what resonates. The cards offer reflection, not certainty.': 'Leve o que fizer sentido. As cartas oferecem reflexão, não certeza.',
    'Oracle Dialogue': 'Diálogo com o Oráculo',
    'The Oracle is listening.': 'O Oráculo está ouvindo.',
    'Reversed': 'Invertida',
    'CHOOSE A FOLLOW-UP': 'ESCOLHA UMA PERGUNTA DE ACOMPANHAMENTO',
    'Or ask in your own words…': 'Ou pergunte com suas próprias palavras…',
    'Ask the Oracle': 'Perguntar ao Oráculo',
    'Ask my free question': 'Fazer minha pergunta gratuita',
    'The Oracle is connecting your symbols…': 'O Oráculo está conectando seus símbolos…',
    'Continue the conversation': 'Continuar a conversa',
    'Ask unlimited follow-ups, revisit saved conversations, and unlock every deep spread with Mystic Plus.': 'Faça perguntas ilimitadas, retorne a conversas salvas e desbloqueie todas as tiragens profundas com o Mystic Plus.',
    'Unlock Oracle Dialogue': 'Desbloquear o Diálogo com o Oráculo',
    'Ask another question': 'Fazer outra pergunta',
    'Return to my reading': 'Voltar à minha leitura',
    'Your card is finding its voice…': 'Sua carta está encontrando sua voz…',
    'The cards are forming a pattern…': 'As cartas estão formando um padrão…',
    'Stay with your first feeling. The full interpretation appears after the final card turns.': 'Fique com sua primeira sensação. A interpretação completa aparecerá depois que a última carta virar.',
    'Your Mystic Path': 'Seu Caminho Mystic',
    'Your inner world becomes visible as you practice.': 'Seu mundo interior se torna visível com a prática.',
    'INNER CONSTELLATION': 'CONSTELAÇÃO INTERIOR',
    'Today’s rituals': 'Rituais de hoje',
    'Small actions turn insight into change. Each ritual grants +15 XP.': 'Pequenas ações transformam percepção em mudança. Cada ritual concede +15 XP.',
    '60-second reset': 'Reinício de 60 segundos',
    'Breathe in for four, out for six.': 'Inspire por quatro e expire por seis.',
    'Name the truth': 'Dê nome à verdade',
    'Write one sentence you have been avoiding.': 'Escreva uma frase que você vem evitando.',
    'Aligned action': 'Ação alinhada',
    'Take the smallest reversible next step.': 'Dê o menor próximo passo reversível.',
    'Mystic rewards': 'Recompensas Mystic',
    'Your practice unlocks cosmetic relics—never better answers.': 'Sua prática desbloqueia relíquias cosméticas, nunca respostas “melhores”.',
    'Moon Dust': 'Poeira Lunar',
    'Oracle Flame': 'Chama do Oráculo',
    'Astral Crown': 'Coroa Astral',
    'Return tomorrow to keep your constellation alive.': 'Volte amanhã para manter sua constelação viva.',
    'CLAIMED': 'RESGATADO',
    'CLAIM': 'RESGATAR',
    'Ritual complete • +15 XP': 'Ritual concluído • +15 XP',
    'ARCANA VAULT': 'COFRE DOS ARCANOS',
    'Every reading can awaken a card.': 'Cada leitura pode despertar uma carta.',
    'The entire deck has answered you.': 'Todo o baralho respondeu a você.',
    'Undiscovered': 'Não descoberta',
    'Your Arcana Vault': 'Seu Cofre dos Arcanos',
    'Locked': 'Bloqueada',
    'UNDISCOVERED': 'NÃO DESCOBERTA',
    'LIGHT': 'LUZ',
    'SHADOW': 'SOMBRA',
    'ALIGNED ACTION': 'AÇÃO ALINHADA',
    'YOUR WEEKLY MYSTIC WRAPPED': 'SEU RESUMO MYSTIC SEMANAL',
    'Your story is waiting for its first signal.': 'Sua história está esperando pelo primeiro sinal.',
    '✦  MYSTIC WRAPPED': '✦  RESUMO MYSTIC',
    'Your first pattern begins with one honest reading.': 'Seu primeiro padrão começa com uma leitura sincera.',
    'REFLECTIONS': 'REFLEXÕES',
    'No card yet': 'Ainda não há nenhuma carta',
    'REPEATING CARD': 'CARTA RECORRENTE',
    'Complete a reading and return here to watch your emotional patterns become visible.': 'Conclua uma leitura e volte aqui para ver seus padrões emocionais se tornarem visíveis.',
    'Begin my first reading': 'Começar minha primeira leitura',
    'Keep building my pattern': 'Continuar construindo meu padrão',
    'First Signal': 'Primeiro Sinal',
    'Save 1 reading': 'Salvar 1 leitura',
    'Flame Keeper': 'Guardião da Chama',
    'Reach a 3-day streak': 'Alcance uma sequência de 3 dias',
    'Arcana Seeker': 'Buscador de Arcanos',
    'Awaken 10 cards': 'Desperte 10 cartas',
    'Relic Keeper': 'Guardião de Relíquias',
    'Claim an XP relic': 'Resgate uma relíquia de XP',
    'Reading preferences': 'Preferências de leitura',
    'Privacy & data': 'Privacidade e dados',
    'Help and support': 'Ajuda e suporte',
    'Your space': 'Seu espaço',
    'LEVEL': 'NÍVEL',
    'day streak': 'dias de sequência',
    'readings': 'leituras',
    'arcana': 'arcanos',
    'Mystic achievements': 'Conquistas Mystic',
    'Your practice leaves permanent marks on your path.': 'Sua prática deixa marcas permanentes no seu caminho.',
    'Your tarot deck': 'Seu baralho de tarô',
    'Choose the visual energy that follows every reading.': 'Escolha a energia visual que acompanhará cada leitura.',
    'Mystic Plus active': 'Mystic Plus ativo',
    'Unlock Mystic Plus': 'Desbloquear Mystic Plus',
    'View plan and manage subscription': 'Ver plano e gerenciar assinatura',
    'Go deeper with unlimited readings': 'Aprofunde-se com leituras ilimitadas',
    'Soul profile': 'Perfil da alma',
    'Language': 'Idioma',
    'Choose language': 'Escolher idioma',
    'Mystic is fully available in English, Turkish, Spanish, and Brazilian Portuguese.': 'Mystic está totalmente disponível em inglês, turco, espanhol e português do Brasil.',
    'Astral Sage': 'Sábio Astral',
    'Mystic Oracle': 'Oráculo Mystic',
    'Mystic Initiate': 'Iniciado Mystic',
    'Love path': 'Caminho do amor',
    'Purpose path': 'Caminho do propósito',
    'Healing path': 'Caminho da cura',
    'Clarity path': 'Caminho da clareza',
    'UNLOCKED': 'DESBLOQUEADO',
    'ACTIVE DECK': 'BARALHO ATIVO',
    'Solar Gold': 'Ouro Solar',
    'Make Mystic yours': 'Deixe Mystic com a sua cara',
    'Your name and intention shape the language, memory, and guidance around every reading.': 'Seu nome e sua intenção moldam a linguagem, a memória e a orientação de cada leitura.',
    'Your name': 'Seu nome',
    'YOUR CURRENT PATH': 'SEU CAMINHO ATUAL',
    'Save my soul profile': 'Salvar meu perfil da alma',
    'Stored privately on this device.': 'Armazenado de forma privada neste dispositivo.',
    'PLUS PREVIEW': 'PRÉVIA DO PLUS',
    'The first signal is forming…': 'O primeiro sinal está se formando…',
    'YOUR FIRST SIGNAL': 'SEU PRIMEIRO SINAL',
    'Reversed energy': 'Energia invertida',
    'Upright energy': 'Energia em pé',
    'The rest of your spread': 'O restante da sua tiragem',
    'Included with Mystic Plus • Cancel anytime': 'Incluído no Mystic Plus • Cancele quando quiser',
    'Shape every reading': 'Molde cada leitura',
    'Allow reversed cards': 'Permitir cartas invertidas',
    'Ritual sound effects': 'Efeitos sonoros do ritual',
    'Reflection-first guidance': 'Orientação centrada na reflexão',
    'Your inner world stays yours': 'Seu mundo interior continua sendo seu',
    'Export my journal': 'Exportar meu diário',
    'Delete all Mystic data': 'Excluir todos os dados do Mystic',
    'Entertainment & reflection': 'Entretenimento e reflexão',
    'We are here to help': 'Estamos aqui para ajudar',
    'Does Mystic predict the future?': 'Mystic prevê o futuro?',
    'Can I cancel Mystic Plus?': 'Posso cancelar o Mystic Plus?',
    'How do I restore a purchase?': 'Como restauro uma compra?',
    'Is my journal private?': 'Meu diário é privado?',
    'Copy support link': 'Copiar link de suporte',
    'Support link copied.': 'Link de suporte copiado.',
    ' (Reversed)': ' (Invertida)',
    'Delete all Mystic data?': 'Excluir todos os dados do Mystic?',
    'Keep my data': 'Manter meus dados',
    'Delete everything': 'Excluir tudo',
    'Your memory map is waiting.': 'Seu mapa de memórias está esperando.',
    'Your patterns, connected.': 'Seus padrões, conectados.',
    'Memory Map': 'Mapa de Memórias',
    'Strongest connection': 'Conexão mais forte',
    'Search by meaning': 'Buscar por significado',
    'No connected memory found yet.': 'Ainda não foi encontrada nenhuma memória conectada.',
    'Daily': 'Diária',
    'Money': 'Dinheiro',
    'Decision': 'Decisão',
    'Spirit': 'Espírito',
    'Shadow': 'Sombra',
    'Future': 'Futuro',
    'Begin before certainty arrives': 'Comece antes que a certeza chegue',
    'Take one small step you can reverse.': 'Dê um pequeno passo que você possa desfazer.',
    'What would I try if I did not need to look ready?': 'O que eu tentaria se não precisasse parecer pronto?',
    'Direct your available power': 'Direcione o poder que você já tem',
    'Choose one tool and use it for fifteen focused minutes.': 'Escolha uma ferramenta e use-a por quinze minutos de foco.',
    'Where am I waiting for a resource I already have?': 'Onde estou esperando por um recurso que já tenho?',
    'Listen beneath the noise': 'Escute por baixo do ruído',
    'Sit without input for three quiet minutes.': 'Fique três minutos em silêncio, sem estímulos.',
    'What does my body know before my mind explains it?': 'O que meu corpo sabe antes que minha mente explique?',
    'Nourish what should grow': 'Nutra o que deve crescer',
    'Improve one condition around your creative work.': 'Melhore uma condição ao redor do seu trabalho criativo.',
    'What becomes possible when I stop starving my own needs?': 'O que se torna possível quando paro de privar minhas próprias necessidades?',
    'Build a kind structure': 'Construa uma estrutura gentil',
    'Create one boundary that makes tomorrow easier.': 'Crie um limite que torne o amanhã mais fácil.',
    'Which rule protects me, and which one only controls me?': 'Qual regra me protege e qual apenas me controla?',
    'Choose your living tradition': 'Escolha sua tradição viva',
    'Keep one useful teaching and question one inherited rule.': 'Mantenha um ensinamento útil e questione uma regra herdada.',
    'What deserves my respect rather than blind obedience?': 'O que merece meu respeito em vez de obediência cega?',
    'Align desire with values': 'Alinhe o desejo aos seus valores',
    'Name the value beneath one important choice.': 'Dê nome ao valor por trás de uma escolha importante.',
    'What choice lets me stay connected without leaving myself?': 'Qual escolha me permite continuar conectado sem me abandonar?',
    'Move with a named direction': 'Avance com uma direção definida',
    'Write your destination before increasing your speed.': 'Escreva seu destino antes de aumentar a velocidade.',
    'Am I moving toward something or merely escaping?': 'Estou indo em direção a algo ou apenas fugindo?',
    'Practice gentle courage': 'Pratique uma coragem gentil',
    'Meet one difficult feeling without trying to defeat it.': 'Encontre uma emoção difícil sem tentar derrotá-la.',
    'What changes when strength no longer means force?': 'O que muda quando força deixa de significar imposição?',
    'Return with your own light': 'Retorne com sua própria luz',
    'Step away from input, then write one honest sentence.': 'Afaste-se dos estímulos e depois escreva uma frase sincera.',
    'Which answer can only be heard in solitude?': 'Qual resposta só pode ser ouvida na solidão?',
    'Work with the turning cycle': 'Trabalhe com o ciclo em movimento',
    'Release one expectation that belongs to yesterday.': 'Solte uma expectativa que pertence a ontem.',
    'What opening appears when I stop demanding the old shape?': 'Qual abertura aparece quando paro de exigir a forma antiga?',
    'Restore honest proportion': 'Restaure uma proporção honesta',
    'Name your part without taking all the blame.': 'Reconheça sua parte sem assumir toda a culpa.',
    'What decision would I respect if nobody applauded?': 'Qual decisão eu respeitaria mesmo que ninguém aplaudisse?',
    'See from the opposite angle': 'Veja pelo ângulo oposto',
    'Argue sincerely for the view you resist.': 'Defenda com sinceridade o ponto de vista ao qual você resiste.',
    'What becomes visible when progress pauses?': 'O que se torna visível quando o progresso faz uma pausa?',
    'Release the completed form': 'Solte a forma que já terminou',
    'Remove one object, task, or promise that is already over.': 'Retire um objeto, uma tarefa ou uma promessa que já terminou.',
    'Which identity can no longer carry me forward?': 'Qual identidade já não consegue me levar adiante?',
    'Integrate instead of swinging': 'Integre em vez de oscilar',
    'Make the next adjustment small enough to sustain.': 'Faça o próximo ajuste pequeno o bastante para ser sustentado.',
    'Where would five percent be wiser than all or nothing?': 'Onde cinco por cento seria mais sábio do que tudo ou nada?',
    'Name the hidden bargain': 'Dê nome ao acordo oculto',
    'Write the real cost of one familiar attachment.': 'Escreva o custo real de um apego conhecido.',
    'What keeps choosing for me when I stop paying attention?': 'O que continua escolhendo por mim quando deixo de prestar atenção?',
    'Protect truth through change': 'Proteja a verdade durante a mudança',
    'Separate what is falling from what is genuinely valuable.': 'Separe o que está caindo do que é realmente valioso.',
    'What false structure am I exhausted from maintaining?': 'Qual estrutura falsa estou cansado de manter?',
    'Practice evidence of hope': 'Pratique evidências de esperança',
    'Do one hopeful act that asks nothing from the outcome.': 'Faça um gesto de esperança que não exija nada do resultado.',
    'What small act would make possibility feel safe again?': 'Qual pequeno gesto faria a possibilidade voltar a parecer segura?',
    'Wait for more light': 'Espere por mais luz',
    'Divide one fear into facts, assumptions, and unknowns.': 'Divida um medo entre fatos, suposições e desconhecidos.',
    'Where has uncertainty been disguised as certainty?': 'Onde a incerteza se disfarçou de certeza?',
    'Let joy be uncomplicated': 'Deixe a alegria ser simples',
    'Share one warm moment without performing it.': 'Compartilhe um momento caloroso sem transformá-lo em atuação.',
    'What goodness am I making harder than it needs to be?': 'Que coisa boa estou tornando mais difícil do que precisa ser?',
    'Answer the deeper call': 'Responda ao chamado mais profundo',
    'Write what the next version of you refuses to postpone.': 'Escreva o que sua próxima versão se recusa a continuar adiando.',
    'Who am I becoming when old shame is not in charge?': 'Quem estou me tornando quando a antiga vergonha já não está no comando?',
    'Honor completion': 'Honre o que se completa',
    'Close one open loop and name what it taught you.': 'Feche um ciclo em aberto e diga o que ele ensinou a você.',
    'What must be celebrated before the next chapter begins?': 'O que precisa ser celebrado antes que o próximo capítulo comece?',
  };

  static final List<_MysticTemplate> _spanishTemplates = <_MysticTemplate>[
    _MysticTemplate('{{p0}} readings connected • Day {{p1}} of 22', '{{p0}} lecturas conectadas • Día {{p1}} de 22'),
    _MysticTemplate('CURRENT CHAPTER • {{p0}}', 'CAPÍTULO ACTUAL • {{p0}}'),
    _MysticTemplate('Your recent {{p0}} questions have carried {{p1}} energy. This chapter asks you to {{p2}}', 'Tus preguntas recientes sobre {{p0}} han llevado una energía {{p1}}. Este capítulo te invita a {{p2}}'),
    _MysticTemplate('Seal day {{p0}}', 'Sellar el día {{p0}}'),
    _MysticTemplate('DAY {{p0}} OF 22', 'DÍA {{p0}} DE 22'),
    _MysticTemplate('Your cards are waiting, {{p0}}', 'Tus cartas te esperan, {{p0}}'),
    _MysticTemplate('{{p0}}-card premium spread', 'Tirada premium de {{p0}} cartas'),
    _MysticTemplate('{{p0}} cards', '{{p0}} cartas'),
    _MysticTemplate('{{p0}} card spread', 'Tirada de {{p0}} cartas'),
    _MysticTemplate('Your {{p0}} path is opening', 'Tu camino de {{p0}} se está abriendo'),
    _MysticTemplate('{{p0}} has returned {{p1}} times. Mystic is watching what this symbol keeps asking you to notice.', '{{p0}} ha regresado {{p1}} veces. Mystic observa qué sigue pidiéndote que notes este símbolo.'),
    _MysticTemplate('You have entered recent readings feeling {{p0}}. Your next reading will hold that emotional thread in view.', 'Has llegado a tus lecturas recientes sintiéndote {{p0}}. Tu próxima lectura tendrá presente ese hilo emocional.'),
    _MysticTemplate('{{p0}} free deep readings left today', 'Te quedan {{p0}} lecturas profundas gratuitas hoy'),
    _MysticTemplate('🔥 {{p0}} day streak  •  +25 XP', '🔥 Racha de {{p0}} días  •  +25 XP'),
    _MysticTemplate('Choose {{p0}} more', 'Elige {{p0}} más'),
    _MysticTemplate('{{p0}}, a hopeful path is becoming visible.', '{{p0}}, empieza a hacerse visible un camino esperanzador.'),
    _MysticTemplate('{{p0}}, the truth arrives when you slow down.', '{{p0}}, la verdad llega cuando bajas el ritmo.'),
    _MysticTemplate('{{p0}} also appeared in your last saved reading. Repeating symbols often become useful when you compare what changed between the two moments.', '{{p0}} también apareció en tu última lectura guardada. Los símbolos repetidos suelen ser útiles cuando comparas qué cambió entre ambos momentos.'),
    _MysticTemplate('Your previous reading began from {{p0}}; today you chose {{p1}}. Mystic is connecting the emotional shift—not just the cards.', 'Tu lectura anterior comenzó desde {{p0}}; hoy elegiste {{p1}}. Mystic está conectando el cambio emocional, no solo las cartas.'),
    _MysticTemplate('{{p0}} Hold this beside your intention of {{p1}}. Let it be an invitation, not a command, and notice what changes over the next twenty-four hours.', '{{p0}} Mantenlo junto a tu intención de {{p1}}. Tómalo como una invitación, no como una orden, y observa qué cambia durante las próximas veinticuatro horas.'),
    _MysticTemplate('Hold your {{p0}} intention in mind. Exhale once, then open the seal when you feel ready.', 'Mantén en mente tu intención de {{p0}}. Exhala una vez y abre el sello cuando te sientas preparado.'),
    _MysticTemplate('{{p0}}, the Oracle is listening.', '{{p0}}, el Oráculo está escuchando.'),
    _MysticTemplate('Ask one question about the cards you just revealed. The answer will stay grounded in their symbols and your {{p0}} path.', 'Haz una pregunta sobre las cartas que acabas de revelar. La respuesta se mantendrá anclada en sus símbolos y en tu camino de {{p0}}.'),
    _MysticTemplate('Oracle Memory is connecting {{p0}} previous readings on this device.', 'La Memoria del Oráculo está conectando {{p0}} lecturas anteriores de este dispositivo.'),
    _MysticTemplate('LEVEL {{p0}}', 'NIVEL {{p0}}'),
    _MysticTemplate('{{p0}} of 78 cards awakened', '{{p0}} de 78 cartas despertadas'),
    _MysticTemplate('{{p0}}% to Level {{p1}}', '{{p0}} % para alcanzar el nivel {{p1}}'),
    _MysticTemplate('{{p0}}-day flame', 'Llama de {{p0}} días'),
    _MysticTemplate('{{p0}} more cards until your next collection milestone.', 'Faltan {{p0}} cartas para tu próximo hito de colección.'),
    _MysticTemplate('{{p0}} awakened • {{p1}} still hidden', '{{p0}} despertadas • {{p1}} aún ocultas'),
    _MysticTemplate('{{p0}} led your week • {{p1}} reflections', '{{p0}} guio tu semana • {{p1}} reflexiones'),
    _MysticTemplate('{{p0}} {{p1}} was your dominant inner weather.', '{{p0}} {{p1}} fue tu clima interior dominante.'),
    _MysticTemplate('Your invitation: notice where {{p0}} energy protected you—and where it quietly chose for you.', 'Tu invitación: observa dónde te protegió la energía {{p0}} y dónde eligió silenciosamente por ti.'),
    _MysticTemplate('{{p0}} XP to level {{p1}}', '{{p0}} XP para alcanzar el nivel {{p1}}'),
    _MysticTemplate('One card is yours. The complete {{p0}}-card story waits behind it.', 'Una carta es tuya. La historia completa de {{p0}} cartas te espera detrás de ella.'),
    _MysticTemplate('{{p0}} LOCKED', '{{p0}} BLOQUEADAS'),
    _MysticTemplate('Unlock the full {{p0}}', 'Desbloquear la lectura completa de {{p0}}'),
    _MysticTemplate('{{p0}} themes', '{{p0}} temas'),
    _MysticTemplate('{{p0}} readings', '{{p0}} lecturas'),
  ];

  static final List<_MysticTemplate> _portugueseBrazilTemplates = <_MysticTemplate>[
    _MysticTemplate('{{p0}} readings connected • Day {{p1}} of 22', '{{p0}} leituras conectadas • Dia {{p1}} de 22'),
    _MysticTemplate('CURRENT CHAPTER • {{p0}}', 'CAPÍTULO ATUAL • {{p0}}'),
    _MysticTemplate('Your recent {{p0}} questions have carried {{p1}} energy. This chapter asks you to {{p2}}', 'Suas perguntas recentes sobre {{p0}} carregaram uma energia {{p1}}. Este capítulo convida você a {{p2}}'),
    _MysticTemplate('Seal day {{p0}}', 'Selar o dia {{p0}}'),
    _MysticTemplate('DAY {{p0}} OF 22', 'DIA {{p0}} DE 22'),
    _MysticTemplate('Your cards are waiting, {{p0}}', 'Suas cartas estão esperando, {{p0}}'),
    _MysticTemplate('{{p0}}-card premium spread', 'Tiragem premium de {{p0}} cartas'),
    _MysticTemplate('{{p0}} cards', '{{p0}} cartas'),
    _MysticTemplate('{{p0}} card spread', 'Tiragem de {{p0}} cartas'),
    _MysticTemplate('Your {{p0}} path is opening', 'Seu caminho de {{p0}} está se abrindo'),
    _MysticTemplate('{{p0}} has returned {{p1}} times. Mystic is watching what this symbol keeps asking you to notice.', '{{p0}} retornou {{p1}} vezes. Mystic observa o que esse símbolo continua pedindo para você notar.'),
    _MysticTemplate('You have entered recent readings feeling {{p0}}. Your next reading will hold that emotional thread in view.', 'Você entrou nas leituras recentes sentindo-se {{p0}}. Sua próxima leitura manterá esse fio emocional em vista.'),
    _MysticTemplate('{{p0}} free deep readings left today', 'Você ainda tem {{p0}} leituras profundas gratuitas hoje'),
    _MysticTemplate('🔥 {{p0}} day streak  •  +25 XP', '🔥 Sequência de {{p0}} dias  •  +25 XP'),
    _MysticTemplate('Choose {{p0}} more', 'Escolha mais {{p0}}'),
    _MysticTemplate('{{p0}}, a hopeful path is becoming visible.', '{{p0}}, um caminho esperançoso começa a ficar visível.'),
    _MysticTemplate('{{p0}}, the truth arrives when you slow down.', '{{p0}}, a verdade chega quando você desacelera.'),
    _MysticTemplate('{{p0}} also appeared in your last saved reading. Repeating symbols often become useful when you compare what changed between the two moments.', '{{p0}} também apareceu na sua última leitura salva. Símbolos repetidos costumam se tornar úteis quando você compara o que mudou entre os dois momentos.'),
    _MysticTemplate('Your previous reading began from {{p0}}; today you chose {{p1}}. Mystic is connecting the emotional shift—not just the cards.', 'Sua leitura anterior começou em {{p0}}; hoje você escolheu {{p1}}. Mystic está conectando a mudança emocional, não apenas as cartas.'),
    _MysticTemplate('{{p0}} Hold this beside your intention of {{p1}}. Let it be an invitation, not a command, and notice what changes over the next twenty-four hours.', '{{p0}} Mantenha isso ao lado da sua intenção de {{p1}}. Encare como um convite, não como uma ordem, e observe o que muda nas próximas vinte e quatro horas.'),
    _MysticTemplate('Hold your {{p0}} intention in mind. Exhale once, then open the seal when you feel ready.', 'Mantenha em mente sua intenção de {{p0}}. Expire uma vez e abra o selo quando se sentir pronto.'),
    _MysticTemplate('{{p0}}, the Oracle is listening.', '{{p0}}, o Oráculo está ouvindo.'),
    _MysticTemplate('Ask one question about the cards you just revealed. The answer will stay grounded in their symbols and your {{p0}} path.', 'Faça uma pergunta sobre as cartas que você acabou de revelar. A resposta permanecerá ancorada nos símbolos delas e no seu caminho de {{p0}}.'),
    _MysticTemplate('Oracle Memory is connecting {{p0}} previous readings on this device.', 'A Memória do Oráculo está conectando {{p0}} leituras anteriores neste dispositivo.'),
    _MysticTemplate('LEVEL {{p0}}', 'NÍVEL {{p0}}'),
    _MysticTemplate('{{p0}} of 78 cards awakened', '{{p0}} de 78 cartas despertas'),
    _MysticTemplate('{{p0}}% to Level {{p1}}', '{{p0}}% para alcançar o nível {{p1}}'),
    _MysticTemplate('{{p0}}-day flame', 'Chama de {{p0}} dias'),
    _MysticTemplate('{{p0}} more cards until your next collection milestone.', 'Faltam {{p0}} cartas para o próximo marco da sua coleção.'),
    _MysticTemplate('{{p0}} awakened • {{p1}} still hidden', '{{p0}} despertas • {{p1}} ainda ocultas'),
    _MysticTemplate('{{p0}} led your week • {{p1}} reflections', '{{p0}} guiou sua semana • {{p1}} reflexões'),
    _MysticTemplate('{{p0}} {{p1}} was your dominant inner weather.', '{{p0}} {{p1}} foi seu clima interior dominante.'),
    _MysticTemplate('Your invitation: notice where {{p0}} energy protected you—and where it quietly chose for you.', 'Seu convite: observe onde a energia {{p0}} protegeu você e onde escolheu silenciosamente por você.'),
    _MysticTemplate('{{p0}} XP to level {{p1}}', '{{p0}} XP para alcançar o nível {{p1}}'),
    _MysticTemplate('One card is yours. The complete {{p0}}-card story waits behind it.', 'Uma carta é sua. A história completa de {{p0}} cartas espera atrás dela.'),
    _MysticTemplate('{{p0}} LOCKED', '{{p0}} BLOQUEADAS'),
    _MysticTemplate('Unlock the full {{p0}}', 'Desbloquear a leitura completa de {{p0}}'),
    _MysticTemplate('{{p0}} themes', '{{p0}} temas'),
    _MysticTemplate('{{p0}} readings', '{{p0}} leituras'),
  ];
}

class _MysticTemplate {
  _MysticTemplate(this.source, this.target)
      : _pattern = RegExp(
          '^${_sourcePattern(source)}\$',
          dotAll: true,
        );

  final String source;
  final String target;
  final RegExp _pattern;

  String? apply(String input, String languageCode) {
    final match = _pattern.firstMatch(input);
    if (match == null) return null;
    var result = target;
    for (var index = 1; index <= match.groupCount; index++) {
      final captured = match.group(index) ?? '';
      result = result.replaceAll(
        '{{p${index - 1}}}',
        MysticTextCatalog._translateCaptured(languageCode, captured),
      );
    }
    return result;
  }

  static String _sourcePattern(String source) {
    final placeholder = RegExp(r'\{\{p\d+\}\}');
    final buffer = StringBuffer();
    var cursor = 0;
    for (final match in placeholder.allMatches(source)) {
      buffer.write(RegExp.escape(source.substring(cursor, match.start)));
      buffer.write('(.+?)');
      cursor = match.end;
    }
    buffer.write(RegExp.escape(source.substring(cursor)));
    return buffer.toString();
  }
}
