import 'app_language.dart';
import 'store_purchase_service.dart';

String localizedStorePurchaseNotice(
  AppLanguage language,
  StorePurchaseNotice notice,
) {
  return switch (notice) {
    StorePurchaseNotice.nativeOnly => localized(
        language,
        english: 'Store purchases are available only in the iOS and Android apps.',
        spanish: 'Las compras están disponibles solo en las aplicaciones de iOS y Android.',
        french: 'Les achats sont disponibles uniquement dans les applications iOS et Android.',
        portugueseBrazil: 'As compras estão disponíveis apenas nos aplicativos para iOS e Android.',
        turkish: 'Mağaza satın alımları yalnızca iOS ve Android uygulamalarında kullanılabilir.',
        italian: 'Gli acquisti sono disponibili solo nelle app iOS e Android.',
        german: 'Käufe sind nur in den iOS- und Android-Apps verfügbar.',
      ),
    StorePurchaseNotice.purchaseStreamUnavailable => localized(
        language,
        english: 'The official store connection could not be reached. Try again later.',
        spanish: 'No se pudo conectar con la tienda oficial. Inténtalo de nuevo más tarde.',
        french: 'La connexion à la boutique officielle est indisponible. Réessayez plus tard.',
        portugueseBrazil: 'Não foi possível acessar a loja oficial. Tente novamente mais tarde.',
        turkish: 'Resmi mağaza bağlantısına ulaşılamadı. Daha sonra tekrar dene.',
        italian: 'Impossibile raggiungere lo store ufficiale. Riprova più tardi.',
        german: 'Die Verbindung zum offiziellen Store ist nicht erreichbar. Versuche es später erneut.',
      ),
    StorePurchaseNotice.storeUnavailable => localized(
        language,
        english: 'The App Store or Google Play is currently unavailable.',
        spanish: 'App Store o Google Play no está disponible en este momento.',
        french: 'L’App Store ou Google Play est momentanément indisponible.',
        portugueseBrazil: 'A App Store ou o Google Play está indisponível no momento.',
        turkish: 'App Store veya Google Play şu anda kullanılamıyor.',
        italian: 'App Store o Google Play non è al momento disponibile.',
        german: 'Der App Store oder Google Play ist derzeit nicht verfügbar.',
      ),
    StorePurchaseNotice.productsNotConfigured => localized(
        language,
        english: 'Monthly and yearly subscriptions are not configured yet.',
        spanish: 'Las suscripciones mensual y anual aún no están configuradas.',
        french: 'Les abonnements mensuel et annuel ne sont pas encore configurés.',
        portugueseBrazil: 'As assinaturas mensal e anual ainda não foram configuradas.',
        turkish: 'Aylık ve yıllık abonelikler henüz yapılandırılmadı.',
        italian: 'Gli abbonamenti mensile e annuale non sono ancora configurati.',
        german: 'Monats- und Jahresabonnements sind noch nicht eingerichtet.',
      ),
    StorePurchaseNotice.productsLoadFailed => localized(
        language,
        english: 'Subscription options could not be loaded. Try again later.',
        spanish: 'No se pudieron cargar las opciones de suscripción. Inténtalo más tarde.',
        french: 'Les options d’abonnement n’ont pas pu être chargées. Réessayez plus tard.',
        portugueseBrazil: 'Não foi possível carregar as opções de assinatura. Tente novamente mais tarde.',
        turkish: 'Abonelik seçenekleri yüklenemedi. Daha sonra tekrar dene.',
        italian: 'Impossibile caricare le opzioni di abbonamento. Riprova più tardi.',
        german: 'Die Abo-Optionen konnten nicht geladen werden. Versuche es später erneut.',
      ),
    StorePurchaseNotice.checkoutUnavailable => localized(
        language,
        english: 'The official store checkout could not be opened.',
        spanish: 'No se pudo abrir el pago de la tienda oficial.',
        french: 'Le paiement de la boutique officielle n’a pas pu être ouvert.',
        portugueseBrazil: 'Não foi possível abrir o pagamento da loja oficial.',
        turkish: 'Resmi mağaza ödeme ekranı açılamadı.',
        italian: 'Impossibile aprire il pagamento dello store ufficiale.',
        german: 'Der offizielle Store-Checkout konnte nicht geöffnet werden.',
      ),
    StorePurchaseNotice.restoreFailed => localized(
        language,
        english: 'Previous purchases could not be restored. Try again later.',
        spanish: 'No se pudieron restaurar las compras anteriores. Inténtalo más tarde.',
        french: 'Les achats précédents n’ont pas pu être restaurés. Réessayez plus tard.',
        portugueseBrazil: 'Não foi possível restaurar as compras anteriores. Tente novamente mais tarde.',
        turkish: 'Önceki satın alımlar geri yüklenemedi. Daha sonra tekrar dene.',
        italian: 'Impossibile ripristinare gli acquisti precedenti. Riprova più tardi.',
        german: 'Frühere Käufe konnten nicht wiederhergestellt werden. Versuche es später erneut.',
      ),
    StorePurchaseNotice.restoreCompleted => localized(
        language,
        english: 'The restore request is complete. Any active purchase will continue to secure verification.',
        spanish: 'La restauración terminó. Cualquier compra activa pasará a una verificación segura.',
        french: 'La restauration est terminée. Tout achat actif passera à la vérification sécurisée.',
        portugueseBrazil: 'A restauração foi concluída. Qualquer compra ativa seguirá para verificação segura.',
        turkish: 'Geri yükleme tamamlandı. Etkin bir satın alım varsa güvenli doğrulamaya geçilecek.',
        italian: 'Il ripristino è completo. Gli acquisti attivi passeranno alla verifica sicura.',
        german: 'Die Wiederherstellung ist abgeschlossen. Aktive Käufe werden sicher geprüft.',
      ),
    StorePurchaseNotice.waitingForConfirmation => localized(
        language,
        english: 'Waiting for confirmation from the official store.',
        spanish: 'Esperando la confirmación de la tienda oficial.',
        french: 'En attente de la confirmation de la boutique officielle.',
        portugueseBrazil: 'Aguardando a confirmação da loja oficial.',
        turkish: 'Resmi mağazadan onay bekleniyor.',
        italian: 'In attesa della conferma dello store ufficiale.',
        german: 'Bestätigung durch den offiziellen Store wird erwartet.',
      ),
    StorePurchaseNotice.verificationRequired => localized(
        language,
        english: 'Purchase received. Secure entitlement verification is required before premium opens.',
        spanish: 'Compra recibida. Se requiere una verificación segura antes de activar premium.',
        french: 'Achat reçu. Une vérification sécurisée est requise avant l’activation de premium.',
        portugueseBrazil: 'Compra recebida. É necessária uma verificação segura antes de liberar o premium.',
        turkish: 'Satın alım alındı. Premium açılmadan önce güvenli hak doğrulaması gerekiyor.',
        italian: 'Acquisto ricevuto. È necessaria una verifica sicura prima di attivare premium.',
        german: 'Kauf empfangen. Vor der Premium-Freischaltung ist eine sichere Prüfung erforderlich.',
      ),
    StorePurchaseNotice.purchaseFailed => localized(
        language,
        english: 'The purchase was not completed. No premium access was activated.',
        spanish: 'La compra no se completó. No se activó el acceso premium.',
        french: 'L’achat n’a pas été finalisé. Aucun accès premium n’a été activé.',
        portugueseBrazil: 'A compra não foi concluída. O acesso premium não foi ativado.',
        turkish: 'Satın alım tamamlanmadı. Premium erişim açılmadı.',
        italian: 'L’acquisto non è stato completato. L’accesso premium non è stato attivato.',
        german: 'Der Kauf wurde nicht abgeschlossen. Premium wurde nicht aktiviert.',
      ),
    StorePurchaseNotice.purchaseCancelled => localized(
        language,
        english: 'The purchase was cancelled. Nothing was charged.',
        spanish: 'La compra fue cancelada. No se realizó ningún cobro.',
        french: 'L’achat a été annulé. Aucun montant n’a été débité.',
        portugueseBrazil: 'A compra foi cancelada. Nenhuma cobrança foi feita.',
        turkish: 'Satın alım iptal edildi. Herhangi bir ücret alınmadı.',
        italian: 'L’acquisto è stato annullato. Non è stato addebitato nulla.',
        german: 'Der Kauf wurde abgebrochen. Es wurde nichts berechnet.',
      ),
  };
}
